// This file is auto-generated by gqlkit. DO NOT EDIT.

import { commentPost as Comment$commentPost, createPost as Mutation$createPost, updatePost as Mutation$updatePost, postComments as Post$postComments, comments as Query$comments, post as Query$post, posts as Query$posts } from "../schema/query.js";

export function createResolvers() {
  return {
    Comment: {
      commentPost: Comment$commentPost,
    },
    Mutation: {
      createPost: Mutation$createPost,
      updatePost: Mutation$updatePost,
    },
    Post: {
      postComments: Post$postComments,
    },
    Query: {
      comments: Query$comments,
      post: Query$post,
      posts: Query$posts,
    },
  };
}
