// This file is auto-generated by gqlkit. DO NOT EDIT.

import { commentPost, comments, createPost, post, postComments, posts, updatePost } from "../schema/query.js";

export function createResolvers() {
  return {
    Comment: {
      commentPost: commentPost,
    },
    Mutation: {
      createPost: createPost,
      updatePost: updatePost,
    },
    Post: {
      postComments: postComments,
    },
    Query: {
      comments: comments,
      post: post,
      posts: posts,
    },
  };
}
