// This file is auto-generated by gqlkit. DO NOT EDIT.

import { createComplexUser as Mutation$createComplexUser, createUserWithDeeplyNested as Mutation$createUserWithDeeplyNested, updateProfileDirectOptionalExcept as Mutation$updateProfileDirectOptionalExcept, updateProfileWithOptionalExcept as Mutation$updateProfileWithOptionalExcept, updateUserDirectNestedUtility as Mutation$updateUserDirectNestedUtility, updateUserWithNestedAndIntersection as Mutation$updateUserWithNestedAndIntersection, updateUserWithNestedUtility as Mutation$updateUserWithNestedUtility, allUsers as Query$allUsers, searchUsersDirectPartialPick as Query$searchUsersDirectPartialPick, searchUsersWithPartialPick as Query$searchUsersWithPartialPick } from "../schema/types.js";

export function createResolvers() {
  return {
    Mutation: {
      createComplexUser: Mutation$createComplexUser,
      createUserWithDeeplyNested: Mutation$createUserWithDeeplyNested,
      updateProfileDirectOptionalExcept: Mutation$updateProfileDirectOptionalExcept,
      updateProfileWithOptionalExcept: Mutation$updateProfileWithOptionalExcept,
      updateUserDirectNestedUtility: Mutation$updateUserDirectNestedUtility,
      updateUserWithNestedAndIntersection: Mutation$updateUserWithNestedAndIntersection,
      updateUserWithNestedUtility: Mutation$updateUserWithNestedUtility,
    },
    Query: {
      allUsers: Query$allUsers,
      searchUsersDirectPartialPick: Query$searchUsersDirectPartialPick,
      searchUsersWithPartialPick: Query$searchUsersWithPartialPick,
    },
  };
}
