// This file is auto-generated by gqlkit. DO NOT EDIT.

import { users } from "../query.js";
import { posts } from "../user.js";

export function createResolvers() {
  return {
    Query: {
      users: users,
    },
    User: {
      posts: posts,
    },
  };
}
