// This file is auto-generated by gqlkit. DO NOT EDIT.

import { users } from "../query.js";
import { posts } from "../user.js";

export function createResolvers(): {
  Query: {
    users: typeof users;
  };
  User: {
    posts: typeof posts;
  };
} {
  return {
    Query: {
      users: users,
    },
    User: {
      posts: posts,
    },
  };
}
