// This file is auto-generated by gqlkit. DO NOT EDIT.

import { bad as Query$bad } from "../schema/types.js";

export function createResolvers() {
  return {
    Query: {
      bad: Query$bad,
    },
  };
}
