// This file is auto-generated by gqlkit. DO NOT EDIT.

import { createUser as Mutation$createUser, getUser as Query$getUser } from "../schema/types.js";

export function createResolvers() {
  return {
    CreateUserPayload: {
      __resolveType: (obj) => obj.__typename,
    },
    GetUserPayload: {
      __resolveType: (obj) => obj.__typename,
    },
    Mutation: {
      createUser: Mutation$createUser,
    },
    Query: {
      getUser: Query$getUser,
    },
  };
}
