// This file is auto-generated by gqlkit. DO NOT EDIT.

import { user, users } from "../resolvers/query.js";

export const resolvers = {
    Query: {
      user: user,
      users: users,
    },
} as const;
