// This file is auto-generated by gqlkit. DO NOT EDIT.

import { GraphQLScalarType } from "graphql";
import { currentDate as Query$currentDate, events as Query$events, eventsSince as Query$eventsSince, eventsUntil as Query$eventsUntil } from "../schema/query.js";
import type { DateTime } from "../schema/scalars.js";

export function createResolvers({ scalars }: {
  scalars: {
    DateTime: GraphQLScalarType<DateTime, DateTime>;
  };
}) {
  return {
    DateTime: scalars.DateTime,
    Query: {
      currentDate: Query$currentDate,
      events: Query$events,
      eventsSince: Query$eventsSince,
      eventsUntil: Query$eventsUntil,
    },
  };
}
