// This file is auto-generated by gqlkit. DO NOT EDIT.

export function createResolvers() {
  return {
    ContainerParts: {
      __resolveType: (obj: { type: string; state: string }) => {
        switch (obj.type) {
          case "text": return "ContainerPartsText";
          case "tool-search":
            switch (obj.state) {
              case "input-available": return "ContainerPartsToolSearchInputAvailable";
              case "output-available": return "ContainerPartsToolSearchOutputAvailable";
              case "output-error": return "ContainerPartsToolSearchOutputError";
              default: return undefined;
            }
          default: return undefined;
        }
      },
    },
  };
}
