// This file is auto-generated by gqlkit. DO NOT EDIT.

import { postAuthor, posts } from "../schema/post.js";

export function createResolvers() {
  return {
    Post: {
      postAuthor: postAuthor,
    },
    Query: {
      posts: posts,
    },
  };
}
