import { Kind } from "graphql";
import { describe, expect, test } from "vitest";
import { buildDocumentNode } from "./ast-builder.js";

describe("buildDocumentNode backward compatibility", () => {
  test("should handle null customScalars (backward compatibility)", () => {
    const result = buildDocumentNode({
      baseTypes: [],
      inputTypes: [],
      typeExtensions: [],
      customScalarNames: null,
      customScalars: null,
      directiveDefinitions: null,
      hasQuery: false,
      hasMutation: false,
      hasErrors: false,
      abstractTypeResolvers: [],
      autoGeneratedUnionNames: [],
      numericEnums: [],
      stringEnumMappings: [],
      diagnostics: [],
    });

    const scalarDefs = result.definitions.filter(
      (def) => def.kind === Kind.SCALAR_TYPE_DEFINITION,
    );

    expect(scalarDefs).toHaveLength(0);
  });

  test("should handle customScalarNames for backward compatibility", () => {
    const result = buildDocumentNode({
      baseTypes: [],
      inputTypes: [],
      typeExtensions: [],
      customScalarNames: ["DateTime", "URL"],
      customScalars: null,
      directiveDefinitions: null,
      hasQuery: false,
      hasMutation: false,
      hasErrors: false,
      abstractTypeResolvers: [],
      autoGeneratedUnionNames: [],
      numericEnums: [],
      stringEnumMappings: [],
      diagnostics: [],
    });

    const scalarDefs = result.definitions.filter(
      (def) => def.kind === Kind.SCALAR_TYPE_DEFINITION,
    );

    expect(scalarDefs).toHaveLength(2);
  });
});
