// This file is auto-generated by gqlkit. DO NOT EDIT.

export function createResolvers() {
  return {
    UserStatus: {
      ACTIVE: "active",
      INACTIVE: "inactive",
      PENDING_REVIEW: "pending-review",
    },
  };
}
