// This file is auto-generated by gqlkit. DO NOT EDIT.

import { widgets as Query$widgets } from "../../src/gqlkit/schema/query.js";

export function createResolvers() {
  return {
    Query: {
      widgets: Query$widgets,
    },
  };
}
