// This file is auto-generated by gqlkit. DO NOT EDIT.

import { GraphQLScalarType } from "graphql";
import { createEvent as Mutation$createEvent } from "../schema/mutation.js";
import { events as Query$events } from "../schema/query.js";
import type { DateTimeInput, DateTimeOutput, DateTimeStringOutput } from "../schema/scalars.js";

export function createResolvers({ scalars }: {
  scalars: {
    DateTime: GraphQLScalarType<DateTimeInput, DateTimeOutput | DateTimeStringOutput>;
  };
}) {
  return {
    DateTime: scalars.DateTime,
    Mutation: {
      createEvent: Mutation$createEvent,
    },
    Query: {
      events: Query$events,
    },
  };
}
