// This file is auto-generated by gqlkit. DO NOT EDIT.

import { streamEvents as Query$streamEvents } from "../schema/query.js";

export function createResolvers() {
  return {
    Query: {
      streamEvents: Query$streamEvents,
    },
    StreamEvent: {
      __resolveType: (obj: { type: string }) => {
        switch (obj.type) {
          case "start": return "StreamEventStart";
          case "end": return "StreamEventEnd";
          default: return undefined;
        }
      },
    },
  };
}
