// This file is auto-generated by gqlkit. DO NOT EDIT.

import { authorOrError, createUser, createUserErrorIsTypeOf, notFoundErrorIsTypeOf, posts, userIsTypeOf } from "../schema/types.js";

export function createResolvers() {
  return {
    CreateUserError: {
      __isTypeOf: createUserErrorIsTypeOf,
    },
    CreateUserPayload: {
      __resolveType: (obj) => obj.__typename,
    },
    Mutation: {
      createUser: createUser,
    },
    NotFoundError: {
      __isTypeOf: notFoundErrorIsTypeOf,
    },
    Post: {
      authorOrError: authorOrError,
    },
    PostAuthorOrErrorPayload: {
      __resolveType: (obj) => obj.__typename,
    },
    Query: {
      posts: posts,
    },
    User: {
      __isTypeOf: userIsTypeOf,
    },
  };
}
