// This file is auto-generated by gqlkit. DO NOT EDIT.

import { eventQuery as Query$eventQuery } from "../schema/query.js";

export function createResolvers() {
  return {
    Event: {
      __resolveType: (obj: { type: string }) => {
        switch (obj.type) {
          case "chart": return "EventChart";
          case "finish": return "EventFinish";
          default: return undefined;
        }
      },
    },
    Query: {
      eventQuery: Query$eventQuery,
    },
  };
}
