// This file is auto-generated by gqlkit. DO NOT EDIT.

import { GraphQLScalarType } from "graphql";
import { events } from "../query.js";
import type { DateTime } from "../../../scalars.js";

export function createResolvers({ scalars }: {
  scalars: {
    DateTime: GraphQLScalarType<DateTime, DateTime>;
  };
}) {
  return {
    DateTime: scalars.DateTime,
    Query: {
      events: events,
    },
  };
}
