import type ts from "typescript";
import { describe, expect, it } from "vitest";
import type {
  ExtractResolversResult,
  GraphQLInputValue,
} from "../resolver-extractor/index.js";
import type {
  ExtractedTypeInfo,
  FieldDefinition,
  InlineEnumMemberInfo,
  InlineObjectPropertyDef,
  TSTypeReference,
} from "../type-extractor/types/index.js";
import {
  type AutoTypeGeneratorInput,
  generateAutoTypes,
} from "./auto-type-generator.js";

function createInlineObjectTsType(
  properties: InlineObjectPropertyDef[],
  nullable = false,
): TSTypeReference {
  return {
    kind: "inlineObject",
    name: null,
    elementType: null,
    members: null,
    nullable,
    scalarInfo: null,
    inlineObjectProperties: properties,
    inlineEnumMembers: null,
    externalEnumSymbol: null,
    externalEnumDescription: null,
    externalEnumDeprecated: null,
  };
}

function createPrimitiveTsType(
  name: string,
  nullable = false,
): TSTypeReference {
  return {
    kind: "primitive",
    name,
    elementType: null,
    members: null,
    nullable,
    scalarInfo: null,
    inlineObjectProperties: null,
    inlineEnumMembers: null,
    externalEnumSymbol: null,
    externalEnumDescription: null,
    externalEnumDeprecated: null,
  };
}

function createProperty(
  name: string,
  tsType: TSTypeReference,
  optional = false,
  description: string | null = null,
): InlineObjectPropertyDef {
  return {
    name,
    tsType,
    optional,
    description,
    deprecated: null,
    directives: null,
    defaultValue: null,
    sourceLocation: null,
  };
}

function createField(
  name: string,
  tsType: TSTypeReference,
  optional = false,
  description: string | null = null,
): FieldDefinition {
  return {
    name,
    tsType,
    optional,
    description,
    deprecated: null,
    directives: null,
    defaultValue: null,
    sourceLocation: null,
  };
}

function createExtractedType(
  name: string,
  fields: FieldDefinition[],
  kind: "object" | "interface" = "object",
): ExtractedTypeInfo {
  return {
    metadata: {
      name,
      kind,
      sourceFile: "src/gqlkit/schema/types.ts",
      sourceLocation: {
        file: "src/gqlkit/schema/types.ts",
        line: 1,
        column: 1,
      },
      exportKind: "named",
      description: null,
      deprecated: null,
      directives: null,
    },
    fields,
    unionMembers: null,
    inlineObjectMembers: null,
    enumMembers: null,
    implementedInterfaces: null,
  };
}

function createEmptyResolversResult(): ExtractResolversResult {
  return {
    queryFields: { fields: [] },
    mutationFields: { fields: [] },
    typeExtensions: [],
    abstractTypeResolvers: [],
    diagnostics: { errors: [], warnings: [] },
  };
}

describe("generateAutoTypes", () => {
  describe("Object type field inline objects", () => {
    it("generates Object type from inline object in Object type field", () => {
      const inlineProperties: InlineObjectPropertyDef[] = [
        createProperty("bio", createPrimitiveTsType("string")),
        createProperty("website", createPrimitiveTsType("string", true)),
      ];

      const extractedTypes: ExtractedTypeInfo[] = [
        createExtractedType("User", [
          createField("id", createPrimitiveTsType("string")),
          createField("profile", createInlineObjectTsType(inlineProperties)),
        ]),
      ];

      const input: AutoTypeGeneratorInput = {
        extractedTypes,
        resolversResult: createEmptyResolversResult(),
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes).toHaveLength(1);

      const autoType = result.autoGeneratedTypes[0]!;
      expect(autoType.name).toBe("UserProfile");
      expect(autoType.kind).toBe("Object");
      expect(autoType.fields).toHaveLength(2);
      expect(autoType.fields!.map((f) => f.name)).toEqual(["bio", "website"]);
      expect(autoType.generatedFrom).toEqual({
        parentTypeName: "User",
        fieldPath: ["profile"],
        context: "typeField",
      });
    });

    it("generates nested Object types recursively", () => {
      const locationProperties: InlineObjectPropertyDef[] = [
        createProperty("latitude", createPrimitiveTsType("number")),
        createProperty("longitude", createPrimitiveTsType("number")),
      ];

      const addressProperties: InlineObjectPropertyDef[] = [
        createProperty("street", createPrimitiveTsType("string")),
        createProperty(
          "location",
          createInlineObjectTsType(locationProperties),
        ),
      ];

      const profileProperties: InlineObjectPropertyDef[] = [
        createProperty("bio", createPrimitiveTsType("string")),
        createProperty("address", createInlineObjectTsType(addressProperties)),
      ];

      const extractedTypes: ExtractedTypeInfo[] = [
        createExtractedType("User", [
          createField("id", createPrimitiveTsType("string")),
          createField("profile", createInlineObjectTsType(profileProperties)),
        ]),
      ];

      const input: AutoTypeGeneratorInput = {
        extractedTypes,
        resolversResult: createEmptyResolversResult(),
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes).toHaveLength(3);

      const typeNames = result.autoGeneratedTypes.map((t) => t.name).sort();
      expect(typeNames).toEqual([
        "UserProfile",
        "UserProfileAddress",
        "UserProfileAddressLocation",
      ]);
    });

    it("preserves description from inline object properties", () => {
      const inlineProperties: InlineObjectPropertyDef[] = [
        createProperty(
          "bio",
          createPrimitiveTsType("string"),
          false,
          "User biography",
        ),
      ];

      const extractedTypes: ExtractedTypeInfo[] = [
        createExtractedType("User", [
          createField(
            "profile",
            createInlineObjectTsType(inlineProperties),
            false,
            "Profile information",
          ),
        ]),
      ];

      const input: AutoTypeGeneratorInput = {
        extractedTypes,
        resolversResult: createEmptyResolversResult(),
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes).toHaveLength(1);
      const autoType = result.autoGeneratedTypes[0]!;
      expect(autoType.fields![0]!.description).toBe("User biography");
    });
  });

  describe("Input type field inline objects", () => {
    it("generates Input Object type from inline object in Input type field", () => {
      const inlineProperties: InlineObjectPropertyDef[] = [
        createProperty("bio", createPrimitiveTsType("string", true)),
        createProperty("age", createPrimitiveTsType("number")),
      ];

      const extractedTypes: ExtractedTypeInfo[] = [
        createExtractedType("CreateUserInput", [
          createField("name", createPrimitiveTsType("string")),
          createField("profile", createInlineObjectTsType(inlineProperties)),
        ]),
      ];

      const input: AutoTypeGeneratorInput = {
        extractedTypes,
        resolversResult: createEmptyResolversResult(),
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes).toHaveLength(1);

      const autoType = result.autoGeneratedTypes[0]!;
      expect(autoType.name).toBe("CreateUserProfileInput");
      expect(autoType.kind).toBe("InputObject");
      expect(autoType.generatedFrom.context).toBe("inputField");
    });

    it("generates nested Input Object types with correct naming", () => {
      const addressProperties: InlineObjectPropertyDef[] = [
        createProperty("street", createPrimitiveTsType("string")),
        createProperty("city", createPrimitiveTsType("string")),
      ];

      const profileProperties: InlineObjectPropertyDef[] = [
        createProperty("bio", createPrimitiveTsType("string", true)),
        createProperty(
          "address",
          createInlineObjectTsType(addressProperties, true),
        ),
      ];

      const extractedTypes: ExtractedTypeInfo[] = [
        createExtractedType("UserInput", [
          createField("profile", createInlineObjectTsType(profileProperties)),
        ]),
      ];

      const input: AutoTypeGeneratorInput = {
        extractedTypes,
        resolversResult: createEmptyResolversResult(),
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes).toHaveLength(2);

      const typeNames = result.autoGeneratedTypes.map((t) => t.name).sort();
      expect(typeNames).toEqual([
        "UserProfileAddressInput",
        "UserProfileInput",
      ]);
    });

    it("preserves defaultValue from inline object properties", () => {
      const inlineProperties: InlineObjectPropertyDef[] = [
        {
          name: "age",
          tsType: createPrimitiveTsType("number"),
          optional: false,
          description: null,
          deprecated: null,
          directives: null,
          defaultValue: { kind: "number", value: 18 },
          sourceLocation: null,
        },
      ];

      const extractedTypes: ExtractedTypeInfo[] = [
        createExtractedType("CreateUserInput", [
          createField("profile", createInlineObjectTsType(inlineProperties)),
        ]),
      ];

      const input: AutoTypeGeneratorInput = {
        extractedTypes,
        resolversResult: createEmptyResolversResult(),
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes).toHaveLength(1);
      const autoType = result.autoGeneratedTypes[0]!;
      expect(autoType.fields![0]!.defaultValue).toEqual({
        kind: "number",
        value: 18,
      });
    });
  });

  describe("Resolver argument inline objects", () => {
    it("generates Input Object type from Query resolver argument", () => {
      const resolversResult: ExtractResolversResult = {
        queryFields: {
          fields: [
            {
              name: "searchUsers",
              type: {
                typeName: "User",
                nullable: false,
                list: true,
                listItemNullable: false,
              },
              args: [
                {
                  name: "filter",
                  type: {
                    typeName: "__INLINE_OBJECT__",
                    nullable: false,
                    list: false,
                    listItemNullable: null,
                  },
                  description: "Search filter",
                  deprecated: null,
                  defaultValue: null,
                  inlineObjectProperties: [
                    createProperty(
                      "namePattern",
                      createPrimitiveTsType("string", true),
                    ),
                    createProperty(
                      "minAge",
                      createPrimitiveTsType("number"),
                      true,
                    ),
                  ],
                } as GraphQLInputValue & {
                  inlineObjectProperties: InlineObjectPropertyDef[];
                },
              ],
              sourceLocation: {
                file: "src/gqlkit/schema/types.ts",
                line: 1,
                column: 1,
              },
              resolverExportName: "searchUsers",
              description: null,
              deprecated: null,
              directives: null,
            },
          ],
        },
        mutationFields: { fields: [] },
        typeExtensions: [],
        abstractTypeResolvers: [],
        diagnostics: { errors: [], warnings: [] },
      };

      const input: AutoTypeGeneratorInput = {
        extractedTypes: [],
        resolversResult,
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes).toHaveLength(1);

      const autoType = result.autoGeneratedTypes[0]!;
      expect(autoType.name).toBe("SearchUsersFilterInput");
      expect(autoType.kind).toBe("InputObject");
      expect(autoType.generatedFrom).toEqual({
        parentTypeName: null,
        fieldPath: ["filter"],
        context: "resolverArg",
      });
    });

    it("generates Input Object type from Mutation resolver argument", () => {
      const resolversResult: ExtractResolversResult = {
        queryFields: { fields: [] },
        mutationFields: {
          fields: [
            {
              name: "createUser",
              type: {
                typeName: "User",
                nullable: false,
                list: false,
                listItemNullable: null,
              },
              args: [
                {
                  name: "data",
                  type: {
                    typeName: "__INLINE_OBJECT__",
                    nullable: false,
                    list: false,
                    listItemNullable: null,
                  },
                  description: "User data",
                  deprecated: null,
                  defaultValue: null,
                  inlineObjectProperties: [
                    createProperty("name", createPrimitiveTsType("string")),
                    createProperty(
                      "email",
                      createPrimitiveTsType("string", true),
                    ),
                  ],
                } as GraphQLInputValue & {
                  inlineObjectProperties: InlineObjectPropertyDef[];
                },
              ],
              sourceLocation: {
                file: "src/gqlkit/schema/types.ts",
                line: 1,
                column: 1,
              },
              resolverExportName: "createUser",
              description: null,
              deprecated: null,
              directives: null,
            },
          ],
        },
        typeExtensions: [],
        abstractTypeResolvers: [],
        diagnostics: { errors: [], warnings: [] },
      };

      const input: AutoTypeGeneratorInput = {
        extractedTypes: [],
        resolversResult,
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes).toHaveLength(1);

      const autoType = result.autoGeneratedTypes[0]!;
      expect(autoType.name).toBe("CreateUserDataInput");
      expect(autoType.kind).toBe("InputObject");
    });

    it("generates Input Object type from Field resolver argument", () => {
      const resolversResult: ExtractResolversResult = {
        queryFields: { fields: [] },
        mutationFields: { fields: [] },
        typeExtensions: [
          {
            targetTypeName: "User",
            fields: [
              {
                name: "posts",
                type: {
                  typeName: "Post",
                  nullable: false,
                  list: true,
                  listItemNullable: false,
                },
                args: [
                  {
                    name: "filter",
                    type: {
                      typeName: "__INLINE_OBJECT__",
                      nullable: true,
                      list: false,
                      listItemNullable: null,
                    },
                    description: "Filter options",
                    deprecated: null,
                    defaultValue: null,
                    inlineObjectProperties: [
                      createProperty(
                        "titlePattern",
                        createPrimitiveTsType("string", true),
                      ),
                    ],
                  } as GraphQLInputValue & {
                    inlineObjectProperties: InlineObjectPropertyDef[];
                  },
                ],
                sourceLocation: {
                  file: "src/gqlkit/schema/types.ts",
                  line: 1,
                  column: 1,
                },
                resolverExportName: "posts",
                description: null,
                deprecated: null,
                directives: null,
              },
            ],
          },
        ],
        abstractTypeResolvers: [],
        diagnostics: { errors: [], warnings: [] },
      };

      const input: AutoTypeGeneratorInput = {
        extractedTypes: [],
        resolversResult,
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes).toHaveLength(1);

      const autoType = result.autoGeneratedTypes[0]!;
      expect(autoType.name).toBe("UserPostsFilterInput");
      expect(autoType.kind).toBe("InputObject");
      expect(autoType.generatedFrom).toEqual({
        parentTypeName: "User",
        fieldPath: ["filter"],
        context: "resolverArg",
      });
    });

    it("generates nested Input Object types from resolver arguments", () => {
      const notificationsProperties: InlineObjectPropertyDef[] = [
        createProperty("email", createPrimitiveTsType("boolean")),
        createProperty("push", createPrimitiveTsType("boolean")),
      ];

      const settingsProperties: InlineObjectPropertyDef[] = [
        createProperty(
          "notifications",
          createInlineObjectTsType(notificationsProperties),
        ),
      ];

      const resolversResult: ExtractResolversResult = {
        queryFields: { fields: [] },
        mutationFields: {
          fields: [
            {
              name: "updateSettings",
              type: {
                typeName: "Result",
                nullable: false,
                list: false,
                listItemNullable: null,
              },
              args: [
                {
                  name: "settings",
                  type: {
                    typeName: "__INLINE_OBJECT__",
                    nullable: false,
                    list: false,
                    listItemNullable: null,
                  },
                  description: null,
                  deprecated: null,
                  defaultValue: null,
                  inlineObjectProperties: settingsProperties,
                } as GraphQLInputValue & {
                  inlineObjectProperties: InlineObjectPropertyDef[];
                },
              ],
              sourceLocation: {
                file: "src/gqlkit/schema/types.ts",
                line: 1,
                column: 1,
              },
              resolverExportName: "updateSettings",
              description: null,
              deprecated: null,
              directives: null,
            },
          ],
        },
        typeExtensions: [],
        abstractTypeResolvers: [],
        diagnostics: { errors: [], warnings: [] },
      };

      const input: AutoTypeGeneratorInput = {
        extractedTypes: [],
        resolversResult,
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes).toHaveLength(2);

      const typeNames = result.autoGeneratedTypes.map((t) => t.name).sort();
      expect(typeNames).toEqual([
        "UpdateSettingsSettingsInput",
        "UpdateSettingsSettingsNotificationsInput",
      ]);
    });
  });

  describe("Updated types with resolved references", () => {
    it("updates extractedTypes with resolved type references", () => {
      const inlineProperties: InlineObjectPropertyDef[] = [
        createProperty("bio", createPrimitiveTsType("string")),
      ];

      const extractedTypes: ExtractedTypeInfo[] = [
        createExtractedType("User", [
          createField("id", createPrimitiveTsType("string")),
          createField("profile", createInlineObjectTsType(inlineProperties)),
        ]),
      ];

      const input: AutoTypeGeneratorInput = {
        extractedTypes,
        resolversResult: createEmptyResolversResult(),
      };

      const result = generateAutoTypes(input);

      const updatedUser = result.updatedExtractedTypes.find(
        (t) => t.metadata.name === "User",
      );
      expect(updatedUser).toBeDefined();

      const profileField = updatedUser!.fields.find(
        (f) => f.name === "profile",
      );
      expect(profileField).toBeDefined();
      expect(profileField!.tsType.kind).toBe("reference");
      expect(profileField!.tsType.name).toBe("UserProfile");
    });

    it("updates resolversResult with resolved type references", () => {
      const resolversResult: ExtractResolversResult = {
        queryFields: {
          fields: [
            {
              name: "createUser",
              type: {
                typeName: "User",
                nullable: false,
                list: false,
                listItemNullable: null,
              },
              args: [
                {
                  name: "input",
                  type: {
                    typeName: "__INLINE_OBJECT__",
                    nullable: false,
                    list: false,
                    listItemNullable: null,
                  },
                  description: null,
                  deprecated: null,
                  defaultValue: null,
                  inlineObjectProperties: [
                    createProperty("name", createPrimitiveTsType("string")),
                  ],
                } as GraphQLInputValue & {
                  inlineObjectProperties: InlineObjectPropertyDef[];
                },
              ],
              sourceLocation: {
                file: "src/gqlkit/schema/types.ts",
                line: 1,
                column: 1,
              },
              resolverExportName: "createUser",
              description: null,
              deprecated: null,
              directives: null,
            },
          ],
        },
        mutationFields: { fields: [] },
        typeExtensions: [],
        abstractTypeResolvers: [],
        diagnostics: { errors: [], warnings: [] },
      };

      const input: AutoTypeGeneratorInput = {
        extractedTypes: [],
        resolversResult,
      };

      const result = generateAutoTypes(input);

      const queryField = result.updatedResolversResult.queryFields.fields[0]!;
      const inputArg = queryField.args![0]!;
      // "input" argName should not result in "InputInput" duplication
      expect(inputArg.type.typeName).toBe("CreateUserInput");
    });
  });

  describe("GeneratedFromInfo tracking", () => {
    it("tracks generation source for object field types", () => {
      const inlineProperties: InlineObjectPropertyDef[] = [
        createProperty("bio", createPrimitiveTsType("string")),
      ];

      const extractedTypes: ExtractedTypeInfo[] = [
        createExtractedType("User", [
          createField("profile", createInlineObjectTsType(inlineProperties)),
        ]),
      ];

      const input: AutoTypeGeneratorInput = {
        extractedTypes,
        resolversResult: createEmptyResolversResult(),
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes[0]!.generatedFrom).toEqual({
        parentTypeName: "User",
        fieldPath: ["profile"],
        context: "typeField",
      });
    });

    it("tracks generation source for input field types", () => {
      const inlineProperties: InlineObjectPropertyDef[] = [
        createProperty("bio", createPrimitiveTsType("string")),
      ];

      const extractedTypes: ExtractedTypeInfo[] = [
        createExtractedType("CreateUserInput", [
          createField("profile", createInlineObjectTsType(inlineProperties)),
        ]),
      ];

      const input: AutoTypeGeneratorInput = {
        extractedTypes,
        resolversResult: createEmptyResolversResult(),
      };

      const result = generateAutoTypes(input);

      expect(result.autoGeneratedTypes[0]!.generatedFrom).toEqual({
        parentTypeName: "CreateUserInput",
        fieldPath: ["profile"],
        context: "inputField",
      });
    });
  });

  describe("Inline enum types (Task 5)", () => {
    function createInlineEnumTsType(
      members: InlineEnumMemberInfo[],
      nullable = false,
      externalEnumSymbol: ts.Symbol | null = null,
    ): TSTypeReference {
      return {
        kind: "inlineEnum",
        name: null,
        elementType: null,
        members: null,
        nullable,
        scalarInfo: null,
        inlineObjectProperties: null,
        inlineEnumMembers: members,
        externalEnumSymbol,
        externalEnumDescription: null,
        externalEnumDeprecated: null,
      };
    }

    function createEnumMember(
      value: string,
      description: string | null = null,
    ): InlineEnumMemberInfo {
      return {
        value,
        description,
        deprecated: null,
      };
    }

    describe("Task 5.1: Generate AutoGeneratedType (kind: Enum) from inline enums", () => {
      it("generates Enum type from inline enum in Object type field", () => {
        const statusMembers = [
          createEnumMember("active"),
          createEnumMember("inactive"),
          createEnumMember("pending"),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("User", [
            createField("id", createPrimitiveTsType("string")),
            createField("status", createInlineEnumTsType(statusMembers)),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(1);
        const autoType = result.autoGeneratedTypes[0]!;
        expect(autoType.name).toBe("UserStatus");
        expect(autoType.kind).toBe("Enum");
        expect(autoType.enumValues).toHaveLength(3);
        expect(autoType.enumValues!.map((v) => v.name)).toEqual([
          "ACTIVE",
          "INACTIVE",
          "PENDING",
        ]);
        expect(autoType.enumValues!.map((v) => v.originalValue)).toEqual([
          "active",
          "inactive",
          "pending",
        ]);
        expect(autoType.fields).toBeNull();
      });

      it("converts enum values to SCREAMING_SNAKE_CASE", () => {
        const statusMembers = [
          createEnumMember("pendingReview"),
          createEnumMember("in_progress"),
          createEnumMember("ALREADY_SCREAMING"),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("Task", [
            createField("status", createInlineEnumTsType(statusMembers)),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(1);
        const autoType = result.autoGeneratedTypes[0]!;
        expect(autoType.enumValues!.map((v) => v.name)).toEqual([
          "PENDING_REVIEW",
          "IN_PROGRESS",
          "ALREADY_SCREAMING",
        ]);
        expect(autoType.enumValues!.map((v) => v.originalValue)).toEqual([
          "pendingReview",
          "in_progress",
          "ALREADY_SCREAMING",
        ]);
      });

      it("sets needsStringEnumMapping when values are converted", () => {
        const statusMembers = [
          createEnumMember("pendingReview"),
          createEnumMember("active"),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("Task", [
            createField("status", createInlineEnumTsType(statusMembers)),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(1);
        const autoType = result.autoGeneratedTypes[0]!;
        expect(autoType.needsStringEnumMapping).toBe(true);
      });

      it("sets needsStringEnumMapping to false when no conversion needed", () => {
        const statusMembers = [
          createEnumMember("ACTIVE"),
          createEnumMember("INACTIVE"),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("Task", [
            createField("status", createInlineEnumTsType(statusMembers)),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(1);
        const autoType = result.autoGeneratedTypes[0]!;
        expect(autoType.needsStringEnumMapping).toBe(false);
      });

      it("generates Enum type from inline enum in Input type field", () => {
        const priorityMembers = [
          createEnumMember("high"),
          createEnumMember("medium"),
          createEnumMember("low"),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("CreateTaskInput", [
            createField("priority", createInlineEnumTsType(priorityMembers)),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(1);
        const autoType = result.autoGeneratedTypes[0]!;
        expect(autoType.name).toBe("CreateTaskPriorityInput");
        expect(autoType.kind).toBe("Enum");
      });

      it("preserves description from inline enum members", () => {
        const statusMembers = [
          { value: "active", description: "User is active", deprecated: null },
          {
            value: "inactive",
            description: "User is inactive",
            deprecated: null,
          },
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("User", [
            createField("status", createInlineEnumTsType(statusMembers)),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(1);
        const autoType = result.autoGeneratedTypes[0]!;
        expect(autoType.enumValues![0]!.description).toBe("User is active");
        expect(autoType.enumValues![1]!.description).toBe("User is inactive");
      });

      it("preserves deprecated info from inline enum members", () => {
        const statusMembers = [
          { value: "active", description: null, deprecated: null },
          {
            value: "legacy",
            description: null,
            deprecated: {
              isDeprecated: true as const,
              reason: "Use 'active' instead",
            },
          },
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("User", [
            createField("status", createInlineEnumTsType(statusMembers)),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(1);
        const autoType = result.autoGeneratedTypes[0]!;
        expect(autoType.enumValues![0]!.deprecated).toBeNull();
        expect(autoType.enumValues![1]!.deprecated).toEqual({
          isDeprecated: true,
          reason: "Use 'active' instead",
        });
      });

      it("generates Enum type from resolver argument inline enum", () => {
        const sortByMembers = [
          createEnumMember("name"),
          createEnumMember("createdAt"),
        ];

        const resolversResult: ExtractResolversResult = {
          queryFields: {
            fields: [
              {
                name: "listUsers",
                type: {
                  typeName: "User",
                  nullable: false,
                  list: true,
                  listItemNullable: false,
                },
                args: [
                  {
                    name: "sortBy",
                    type: {
                      typeName: "__INLINE_ENUM__",
                      nullable: false,
                      list: false,
                      listItemNullable: null,
                    },
                    description: "Sort field",
                    deprecated: null,
                    defaultValue: null,
                    inlineObjectProperties: null,
                    inlineEnumMembers: sortByMembers,
                    externalEnumSymbol: null,
                    externalEnumDescription: null,
                    externalEnumDeprecated: null,
                  } satisfies GraphQLInputValue,
                ],
                sourceLocation: {
                  file: "src/gqlkit/schema/resolvers.ts",
                  line: 10,
                  column: 1,
                },
                resolverExportName: "listUsers",
                description: null,
                deprecated: null,
                directives: null,
              },
            ],
          },
          mutationFields: { fields: [] },
          typeExtensions: [],
          abstractTypeResolvers: [],
          diagnostics: { errors: [], warnings: [] },
        };

        const input: AutoTypeGeneratorInput = {
          extractedTypes: [],
          resolversResult,
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(1);
        const autoType = result.autoGeneratedTypes[0]!;
        expect(autoType.name).toBe("ListUsersSortByInput");
        expect(autoType.kind).toBe("Enum");
        expect(autoType.enumValues!.map((v) => v.name)).toEqual([
          "NAME",
          "CREATED_AT",
        ]);
      });
    });

    describe("Task 5.2: Deduplicate external TypeScript enums with same symbol", () => {
      it("merges multiple references to the same external enum symbol into single type", () => {
        const mockSymbol = { name: "Status" } as unknown as ts.Symbol;
        const statusMembers = [
          createEnumMember("active"),
          createEnumMember("inactive"),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("User", [
            createField(
              "status",
              createInlineEnumTsType(statusMembers, false, mockSymbol),
            ),
          ]),
          createExtractedType("Post", [
            createField(
              "status",
              createInlineEnumTsType(statusMembers, false, mockSymbol),
            ),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(1);
        const autoType = result.autoGeneratedTypes[0]!;
        expect(autoType.kind).toBe("Enum");
      });

      it("uses first occurrence name for merged external enum", () => {
        const mockSymbol = { name: "SharedStatus" } as unknown as ts.Symbol;
        const statusMembers = [
          createEnumMember("active"),
          createEnumMember("inactive"),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("User", [
            createField(
              "accountStatus",
              createInlineEnumTsType(statusMembers, false, mockSymbol),
            ),
          ]),
          createExtractedType("Post", [
            createField(
              "publishStatus",
              createInlineEnumTsType(statusMembers, false, mockSymbol),
            ),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(1);
        expect(result.autoGeneratedTypes[0]!.name).toBe("UserAccountStatus");
      });

      it("updates all field references to use the merged type name", () => {
        const mockSymbol = { name: "Status" } as unknown as ts.Symbol;
        const statusMembers = [
          createEnumMember("active"),
          createEnumMember("inactive"),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("User", [
            createField(
              "status",
              createInlineEnumTsType(statusMembers, false, mockSymbol),
            ),
          ]),
          createExtractedType("Post", [
            createField(
              "status",
              createInlineEnumTsType(statusMembers, false, mockSymbol),
            ),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        const userType = result.updatedExtractedTypes.find(
          (t) => t.metadata.name === "User",
        );
        const postType = result.updatedExtractedTypes.find(
          (t) => t.metadata.name === "Post",
        );

        expect(userType!.fields[0]!.tsType.name).toBe("UserStatus");
        expect(postType!.fields[0]!.tsType.name).toBe("UserStatus");
      });
    });

    describe("Task 5.3: String literal unions get independent types", () => {
      it("generates independent types for same members at different locations", () => {
        const sameMembers1 = [
          createEnumMember("active"),
          createEnumMember("inactive"),
        ];
        const sameMembers2 = [
          createEnumMember("active"),
          createEnumMember("inactive"),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("User", [
            createField("status", createInlineEnumTsType(sameMembers1)),
          ]),
          createExtractedType("Post", [
            createField("status", createInlineEnumTsType(sameMembers2)),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(2);
        const typeNames = result.autoGeneratedTypes.map((t) => t.name).sort();
        expect(typeNames).toEqual(["PostStatus", "UserStatus"]);
      });

      it("string literal unions without symbol are not deduplicated", () => {
        const members1 = [
          createEnumMember("high"),
          createEnumMember("medium"),
          createEnumMember("low"),
        ];
        const members2 = [
          createEnumMember("high"),
          createEnumMember("medium"),
          createEnumMember("low"),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("Task", [
            createField("priority", createInlineEnumTsType(members1)),
          ]),
          createExtractedType("Bug", [
            createField("priority", createInlineEnumTsType(members2)),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(2);
        expect(result.autoGeneratedTypes[0]!.kind).toBe("Enum");
        expect(result.autoGeneratedTypes[1]!.kind).toBe("Enum");
      });
    });

    describe("Mixed inline objects and enums", () => {
      it("generates both Object and Enum types from same parent type", () => {
        const statusMembers = [
          createEnumMember("active"),
          createEnumMember("inactive"),
        ];

        const profileProperties: InlineObjectPropertyDef[] = [
          createProperty("bio", createPrimitiveTsType("string")),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("User", [
            createField("status", createInlineEnumTsType(statusMembers)),
            createField("profile", createInlineObjectTsType(profileProperties)),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        expect(result.autoGeneratedTypes).toHaveLength(2);

        const enumType = result.autoGeneratedTypes.find(
          (t) => t.kind === "Enum",
        );
        const objectType = result.autoGeneratedTypes.find(
          (t) => t.kind === "Object",
        );

        expect(enumType).toBeDefined();
        expect(enumType!.name).toBe("UserStatus");
        expect(objectType).toBeDefined();
        expect(objectType!.name).toBe("UserProfile");
      });

      it("updates extractedTypes with both resolved enum and object references", () => {
        const statusMembers = [
          createEnumMember("active"),
          createEnumMember("inactive"),
        ];

        const profileProperties: InlineObjectPropertyDef[] = [
          createProperty("bio", createPrimitiveTsType("string")),
        ];

        const extractedTypes: ExtractedTypeInfo[] = [
          createExtractedType("User", [
            createField("status", createInlineEnumTsType(statusMembers)),
            createField("profile", createInlineObjectTsType(profileProperties)),
          ]),
        ];

        const input: AutoTypeGeneratorInput = {
          extractedTypes,
          resolversResult: createEmptyResolversResult(),
        };

        const result = generateAutoTypes(input);

        const updatedUser = result.updatedExtractedTypes.find(
          (t) => t.metadata.name === "User",
        );
        expect(updatedUser).toBeDefined();

        const statusField = updatedUser!.fields.find(
          (f) => f.name === "status",
        );
        const profileField = updatedUser!.fields.find(
          (f) => f.name === "profile",
        );

        expect(statusField!.tsType.kind).toBe("reference");
        expect(statusField!.tsType.name).toBe("UserStatus");
        expect(profileField!.tsType.kind).toBe("reference");
        expect(profileField!.tsType.name).toBe("UserProfile");
      });
    });
  });
});
