import type { ExtractedTypeInfo } from "../type-extractor/index.js";
import {
  type AutoGeneratedType,
  generateObjectTypeFromInlineObject,
} from "./auto-type-generator.js";
import { generateDiscriminatorMemberName } from "./discriminator-naming.js";

export interface MemberValueTuple {
  readonly memberTypeName: string | null;
  readonly memberIndex: number;
  readonly values: ReadonlyArray<string | null>;
  readonly isInlineObject: boolean;
}

export interface ValidatedDiscriminatorEntry {
  readonly unionTypeName: string;
  readonly fieldNames: ReadonlyArray<string>;
  readonly memberValueTuples: ReadonlyArray<MemberValueTuple>;
}

export interface DiscriminatorValueMapping {
  readonly memberGraphQLTypeName: string;
  readonly values: ReadonlyArray<string | null>;
}

export interface DiscriminatorResolveTypeInfo {
  readonly unionTypeName: string;
  readonly fieldNames: ReadonlyArray<string>;
  readonly valueMappings: ReadonlyArray<DiscriminatorValueMapping>;
}

export interface CollectDiscriminatorResolveTypesParams {
  readonly validatedEntries: ReadonlyArray<ValidatedDiscriminatorEntry>;
  readonly manualResolveTypeNames: ReadonlySet<string>;
  readonly extractedTypes: ReadonlyArray<ExtractedTypeInfo>;
  readonly typeMap: ReadonlyMap<string, ExtractedTypeInfo>;
}

export interface CollectDiscriminatorResolveTypesResult {
  readonly discriminatorResolveTypes: ReadonlyArray<DiscriminatorResolveTypeInfo>;
  readonly discriminatorResolveTypeNames: ReadonlySet<string>;
  readonly generatedObjectTypes: ReadonlyArray<AutoGeneratedType>;
}

/**
 * Determines the GraphQL type name for a union member based on discriminator values.
 * Named members use their existing type name; inline members get a generated name.
 */
function resolveGraphQLTypeName(
  tuple: MemberValueTuple,
  unionTypeName: string,
): string {
  if (tuple.memberTypeName !== null) {
    return tuple.memberTypeName;
  }

  return generateDiscriminatorMemberName({
    unionTypeName,
    values: tuple.values,
  });
}

/**
 * Collects resolveType pattern information from validated discriminator field entries.
 *
 * For each validated entry:
 * - Skips unions that have manual defineResolveType
 * - Maps discriminator field values to GraphQL type names
 * - Generates object types for inline members
 * - Adds union names to discriminatorResolveTypeNames to suppress MISSING_ABSTRACT_TYPE_RESOLVER
 */
export function collectDiscriminatorResolveTypes(
  params: CollectDiscriminatorResolveTypesParams,
): CollectDiscriminatorResolveTypesResult {
  const { validatedEntries, manualResolveTypeNames, typeMap } = params;

  const discriminatorResolveTypes: DiscriminatorResolveTypeInfo[] = [];
  const discriminatorResolveTypeNames = new Set<string>();
  const generatedObjectTypes: AutoGeneratedType[] = [];

  for (const entry of validatedEntries) {
    // Skip unions that have a manual defineResolveType
    if (manualResolveTypeNames.has(entry.unionTypeName)) {
      continue;
    }

    const unionType = typeMap.get(entry.unionTypeName);
    if (unionType === undefined) {
      continue;
    }

    const valueMappings: DiscriminatorValueMapping[] = [];
    const inlineObjectMembers = unionType.inlineObjectMembers ?? [];
    const namedMemberCount = unionType.unionMembers?.length ?? 0;

    for (const tuple of entry.memberValueTuples) {
      const graphQLTypeName = resolveGraphQLTypeName(
        tuple,
        entry.unionTypeName,
      );

      valueMappings.push({
        memberGraphQLTypeName: graphQLTypeName,
        values: tuple.values,
      });

      // Generate object types for inline members
      if (tuple.isInlineObject) {
        const inlineIndex = tuple.memberIndex - namedMemberCount;
        const inlineMember = inlineObjectMembers[inlineIndex];
        if (inlineMember !== undefined) {
          const objectType = generateObjectTypeFromInlineObject({
            inlineObjectMember: inlineMember,
            typeName: graphQLTypeName,
            abstractTypeName: entry.unionTypeName,
            sourceFile: unionType.metadata.sourceFile,
            skipPropertyNames: new Set(),
          });
          generatedObjectTypes.push(objectType);
        }
      }
    }

    discriminatorResolveTypes.push({
      unionTypeName: entry.unionTypeName,
      fieldNames: entry.fieldNames,
      valueMappings,
    });

    discriminatorResolveTypeNames.add(entry.unionTypeName);
  }

  return {
    discriminatorResolveTypes,
    discriminatorResolveTypeNames,
    generatedObjectTypes,
  };
}
