export {
  type AutoGeneratedField,
  type AutoGeneratedType,
  type AutoTypeGeneratorInput,
  type AutoTypeGeneratorResult,
  type GeneratedFromInfo,
  generateAutoTypes,
} from "./auto-type-generator.js";
export {
  type NameCollisionValidatorInput,
  type NameCollisionValidatorResult,
  type UserDefinedTypeInfo,
  validateNameCollisions,
} from "./name-collision-validator.js";
export type {
  AutoTypeNameContext,
  InputFieldContext,
  ObjectFieldContext,
  ResolverArgContext,
} from "./naming-convention.js";
