/**
 * Information about an auto-generated __resolveType function for a Union type.
 * The generated function returns `obj.__typename` to resolve the concrete type.
 */
export interface AutoGeneratedResolveType {
  /** The name of the Union type */
  readonly unionTypeName: string;
}

/**
 * Parameters for collecting auto-generated __resolveType functions.
 */
export interface CollectAutoResolveTypesParams {
  /** Names of auto-generated Union types (Payload types) */
  readonly autoGeneratedUnionNames: ReadonlyArray<string>;
  /** Names of types that have manually defined defineResolveType */
  readonly manualResolveTypeNames: ReadonlySet<string>;
}

/**
 * Collect auto-generated __resolveType functions for Union types.
 *
 * Auto-generates __resolveType for Union Payload types that:
 * 1. Are auto-generated (not in knownTypeNames)
 * 2. Don't have a manual defineResolveType defined
 *
 * The generated function returns `obj.__typename` which works for:
 * - Inline union members with __typename property
 * - Falls back to __isTypeOf for members without __typename
 */
export function collectAutoResolveTypes(
  params: CollectAutoResolveTypesParams,
): AutoGeneratedResolveType[] {
  const { autoGeneratedUnionNames, manualResolveTypeNames } = params;

  const result: AutoGeneratedResolveType[] = [];

  for (const unionTypeName of autoGeneratedUnionNames) {
    if (manualResolveTypeNames.has(unionTypeName)) {
      continue;
    }

    result.push({ unionTypeName });
  }

  return result.sort((a, b) => a.unionTypeName.localeCompare(b.unionTypeName));
}
