// This file is auto-generated by gqlkit. DO NOT EDIT.

export function createResolvers() {
  return {
    UserStatus: {
      ACTIVE: "USER_STATUS_ACTIVE",
      INACTIVE: "USER_STATUS_INACTIVE",
      PENDING: "USER_STATUS_PENDING",
    },
  };
}
