// This file is auto-generated by gqlkit. DO NOT EDIT.

import type { GraphQLScalarType } from "graphql";
import {
  createPost as Mutation$createPost,
  author as Post$author,
  allPosts as Query$allPosts,
  post as Query$post,
} from "../schema/post.js";
import type { DateTime } from "../schema/scalars.js";
import {
  createUser as Mutation$createUser,
  allUsers as Query$allUsers,
  user as Query$user,
  posts as User$posts,
} from "../schema/user.js";

export function createResolvers({
  scalars,
}: {
  scalars: {
    DateTime: GraphQLScalarType<DateTime, DateTime>;
  };
}) {
  return {
    PostPriority: {
      LOW: "low",
      MEDIUM: "medium",
      HIGH: "high",
    },
    UserStatus: {
      ACTIVE: "active",
      INACTIVE: "inactive",
      SUSPENDED: "suspended",
    },
    CreatePostPriorityInput: {
      LOW: "low",
      MEDIUM: "medium",
      HIGH: "high",
    },
    CreateUserStatusInput: {
      ACTIVE: "active",
      INACTIVE: "inactive",
      SUSPENDED: "suspended",
    },
    DateTime: scalars.DateTime,
    Mutation: {
      createPost: Mutation$createPost,
      createUser: Mutation$createUser,
    },
    Post: {
      author: Post$author,
    },
    Query: {
      allPosts: Query$allPosts,
      allUsers: Query$allUsers,
      post: Query$post,
      user: Query$user,
    },
    User: {
      posts: User$posts,
    },
  };
}
