// This file is auto-generated by gqlkit. DO NOT EDIT.

import { updateSettings } from "../schema/nested.js";
import { createUser, posts, searchUsers, users } from "../schema/types.js";

export function createResolvers() {
  return {
    Mutation: {
      createUser: createUser,
      updateSettings: updateSettings,
    },
    Query: {
      searchUsers: searchUsers,
      users: users,
    },
    User: {
      posts: posts,
    },
  };
}
