// This file is auto-generated by gqlkit. DO NOT EDIT.

import { searchResultResolveType } from "../schema/types.js";

export function createResolvers() {
  return {
    SearchResult: {
      __resolveType: searchResultResolveType,
    },
  };
}
