// This file is auto-generated by gqlkit. DO NOT EDIT.

import { createUser } from "../mutation.js";

export function createResolvers(): {
  Mutation: {
    createUser: typeof createUser;
  };
} {
  return {
    Mutation: {
      createUser: createUser,
    },
  };
}
