import path from "node:path";
import type { DocumentNode } from "graphql";
import type {
  AutoGeneratedResolveType,
  DiscriminatorResolveTypeInfo,
} from "../../auto-type-generator/index.js";
import type { ImportExtension } from "../../config/types.js";
import { TYPENAME_FIELD_NAMES } from "../../core/index.js";
import { toPosixPath } from "../../shared/index.js";
import type { CollectedScalarType } from "../../type-extractor/index.js";
import type {
  NumericEnumInfo,
  StringEnumMappingInfo,
} from "../integrator/result-integrator.js";
import type {
  AbstractTypeResolverInfo,
  FieldResolver,
  ResolverInfo,
  TypeResolvers,
} from "../resolver-collector/resolver-collector.js";
import { buildDiscriminatorResolveTypeEntry } from "./discriminator-resolve-type-emitter.js";

const GENERATED_FILE_HEADER =
  "// This file is auto-generated by gqlkit. DO NOT EDIT.";

export function emitTypeDefsCode(documentNode: DocumentNode): string {
  const documentNodeCode = JSON.stringify(documentNode, null, 2);

  return `${GENERATED_FILE_HEADER}

import type { DocumentNode } from "graphql";

export const typeDefs: DocumentNode = ${documentNodeCode} as DocumentNode;
`;
}

function applyExtension(
  relativePath: string,
  importExtension: ImportExtension,
): string {
  switch (importExtension) {
    case "js":
      return relativePath.replace(/\.ts$/, ".js");
    case "ts":
      return relativePath;
    case "none":
      return relativePath.replace(/\.ts$/, "");
  }
}

interface ComputeRelativeImportPathParams {
  readonly fromDir: string;
  readonly toFile: string;
  readonly importExtension: ImportExtension;
}

function computeRelativeImportPath(
  params: ComputeRelativeImportPathParams,
): string {
  const { fromDir, toFile, importExtension } = params;
  const relativePath = toPosixPath(path.relative(fromDir, toFile));
  const withExt = applyExtension(relativePath, importExtension);
  if (!withExt.startsWith(".")) {
    return `./${withExt}`;
  }
  return withExt;
}

interface ScalarTypeImport {
  readonly typeName: string;
  readonly sourceFile: string;
}

function collectScalarTypeImports(
  customScalars: ReadonlyArray<CollectedScalarType>,
): ScalarTypeImport[] {
  const imports: ScalarTypeImport[] = [];
  const seen = new Set<string>();

  for (const scalar of customScalars) {
    if (
      scalar.inputType &&
      scalar.inputType.sourceFile !== "" &&
      !seen.has(scalar.inputType.typeName)
    ) {
      imports.push({
        typeName: scalar.inputType.typeName,
        sourceFile: scalar.inputType.sourceFile,
      });
      seen.add(scalar.inputType.typeName);
    }

    for (const outputType of scalar.outputTypes) {
      if (outputType.sourceFile !== "" && !seen.has(outputType.typeName)) {
        imports.push({
          typeName: outputType.typeName,
          sourceFile: outputType.sourceFile,
        });
        seen.add(outputType.typeName);
      }
    }
  }

  return imports;
}

interface BuildScalarTypeImportsParams {
  readonly scalarTypeImports: ScalarTypeImport[];
  readonly outputDir: string;
  readonly importExtension: ImportExtension;
}

function buildScalarTypeImports(
  params: BuildScalarTypeImportsParams,
): string[] {
  const { scalarTypeImports, outputDir, importExtension } = params;
  const importsByFile = new Map<string, string[]>();

  for (const imp of scalarTypeImports) {
    const existing = importsByFile.get(imp.sourceFile) ?? [];
    existing.push(imp.typeName);
    importsByFile.set(imp.sourceFile, existing);
  }

  const imports: string[] = [];
  const sortedFiles = [...importsByFile.keys()].sort();

  for (const sourceFile of sortedFiles) {
    const typeNames = importsByFile.get(sourceFile) ?? [];
    const importPath = computeRelativeImportPath({
      fromDir: outputDir,
      toFile: sourceFile,
      importExtension,
    });
    imports.push(
      `import type { ${typeNames.sort().join(", ")} } from "${importPath}";`,
    );
  }

  return imports;
}

function buildScalarTypeParameter(scalar: CollectedScalarType): string {
  const inputTypeName = scalar.inputType?.typeName ?? "unknown";
  const outputTypeNames = scalar.outputTypes.map((t) => t.typeName);
  const outputTypeUnion =
    outputTypeNames.length > 0 ? outputTypeNames.join(" | ") : "unknown";
  return `GraphQLScalarType<${inputTypeName}, ${outputTypeUnion}>`;
}

function buildScalarsArgumentType(
  customScalars: ReadonlyArray<CollectedScalarType>,
): string {
  const entries = customScalars
    .map((scalar) => {
      const typeParam = buildScalarTypeParameter(scalar);
      return `    ${scalar.scalarName}: ${typeParam};`;
    })
    .join("\n");

  return `{\n  scalars: {\n${entries}\n  };\n}`;
}

function buildScalarResolverEntries(
  customScalars: ReadonlyArray<CollectedScalarType>,
): string[] {
  return customScalars.map(
    (scalar) => `    ${scalar.scalarName}: scalars.${scalar.scalarName},`,
  );
}

/**
 * Information about a resolver import with a unique alias.
 */
interface ResolverImportInfo {
  /** The original export name from the source file */
  readonly originalName: string;
  /** The unique local name using the pattern <Parent>$<field> */
  readonly localName: string;
}

interface MakeResolverLocalNameParams {
  readonly parentType: string;
  readonly fieldName: string;
}

/**
 * Creates a unique local name for a resolver import.
 * Format: <ParentType>$<FieldName>
 */
function makeResolverLocalName(params: MakeResolverLocalNameParams): string {
  const { parentType, fieldName } = params;
  return `${parentType}$${fieldName}`;
}

/**
 * Collects resolver imports with unique aliases.
 * Uses the pattern <Parent>$<field> for alias names.
 *
 * Note: Uniqueness assumes no duplicate resolver definitions for the same
 * (parentType, fieldName) pair. Duplicate field definitions are caught
 * by GraphQL schema validation at build time.
 */
function collectResolverImports(
  resolverInfo: ResolverInfo,
): Map<string, ResolverImportInfo[]> {
  const importsByFile = new Map<string, ResolverImportInfo[]>();
  // Track seen localNames per file to avoid duplicate import specifiers
  const seenByFile = new Map<string, Set<string>>();

  for (const type of resolverInfo.types) {
    for (const field of type.fields) {
      const localName = makeResolverLocalName({
        parentType: type.typeName,
        fieldName: field.fieldName,
      });

      const seen = seenByFile.get(field.sourceFile) ?? new Set<string>();
      if (seen.has(localName)) {
        continue;
      }
      seen.add(localName);
      seenByFile.set(field.sourceFile, seen);

      const infos = importsByFile.get(field.sourceFile) ?? [];
      infos.push({ originalName: field.resolverValueName, localName });
      importsByFile.set(field.sourceFile, infos);
    }
  }

  for (const abstractResolver of resolverInfo.abstractTypeResolvers) {
    const localName = makeResolverLocalName({
      parentType: abstractResolver.typeName,
      fieldName: abstractResolver.resolverKey,
    });

    const seen =
      seenByFile.get(abstractResolver.sourceFile) ?? new Set<string>();
    if (seen.has(localName)) {
      continue;
    }
    seen.add(localName);
    seenByFile.set(abstractResolver.sourceFile, seen);

    const infos = importsByFile.get(abstractResolver.sourceFile) ?? [];
    infos.push({ originalName: abstractResolver.exportName, localName });
    importsByFile.set(abstractResolver.sourceFile, infos);
  }

  return importsByFile;
}

interface BuildResolverImportsParams {
  readonly importsByFile: Map<string, ResolverImportInfo[]>;
  readonly outputDir: string;
  readonly importExtension: ImportExtension;
}

function buildResolverImports(params: BuildResolverImportsParams): string[] {
  const { importsByFile, outputDir, importExtension } = params;
  const imports: string[] = [];
  const sortedFiles = [...importsByFile.keys()].sort();

  for (const sourceFile of sortedFiles) {
    const importInfos = importsByFile.get(sourceFile) ?? [];
    const importPath = computeRelativeImportPath({
      fromDir: outputDir,
      toFile: sourceFile,
      importExtension,
    });

    // Sort by localName for consistent output
    const sortedInfos = [...importInfos].sort((a, b) =>
      a.localName.localeCompare(b.localName),
    );

    if (sortedInfos.length > 0) {
      const importSpecifiers = sortedInfos.map(
        (info) => `${info.originalName} as ${info.localName}`,
      );

      imports.push(
        `import { ${importSpecifiers.join(", ")} } from "${importPath}";`,
      );
    }
  }

  return imports;
}

function buildAbstractOnlyTypeEntry(
  abstractResolver: AbstractTypeResolverInfo,
): string {
  const localName = makeResolverLocalName({
    parentType: abstractResolver.typeName,
    fieldName: abstractResolver.resolverKey,
  });
  return `    ${abstractResolver.typeName}: {\n      ${abstractResolver.resolverKey}: ${localName},\n    },`;
}

function buildNumericEnumResolver(enumInfo: NumericEnumInfo): string {
  const entries = enumInfo.members
    .map((member) => `      ${member.name}: ${member.numericValue},`)
    .join("\n");
  return `    ${enumInfo.enumName}: {\n${entries}\n    },`;
}

function buildNumericEnumResolvers(
  numericEnums: ReadonlyArray<NumericEnumInfo>,
): string[] {
  return numericEnums.map(buildNumericEnumResolver);
}

function buildStringEnumResolver(enumInfo: StringEnumMappingInfo): string {
  const entries = enumInfo.members
    .map(
      (member) => `      ${member.graphqlValue}: "${member.typescriptValue}",`,
    )
    .join("\n");
  return `    ${enumInfo.enumName}: {\n${entries}\n    },`;
}

function buildStringEnumResolvers(
  stringEnumMappings: ReadonlyArray<StringEnumMappingInfo>,
): string[] {
  return stringEnumMappings.map(buildStringEnumResolver);
}

function buildFieldResolverValue(
  localName: string,
  field: FieldResolver,
): string {
  if (field.isDirectExport) {
    return localName;
  }
  return `${localName}.${field.fieldName}`;
}

function buildTypeResolverEntry(
  type: TypeResolvers,
  abstractResolverForType: AbstractTypeResolverInfo | null,
): string {
  const entries: string[] = [];
  const isSubscription = type.typeName === "Subscription";

  for (const field of type.fields) {
    const localName = makeResolverLocalName({
      parentType: type.typeName,
      fieldName: field.fieldName,
    });
    const resolverValue = buildFieldResolverValue(localName, field);

    if (isSubscription) {
      entries.push(
        `      ${field.fieldName}: { subscribe: ${resolverValue}, resolve: (event: unknown) => event },`,
      );
    } else {
      entries.push(`      ${field.fieldName}: ${resolverValue},`);
    }
  }

  if (abstractResolverForType !== null) {
    const localName = makeResolverLocalName({
      parentType: abstractResolverForType.typeName,
      fieldName: abstractResolverForType.resolverKey,
    });
    entries.push(`      ${abstractResolverForType.resolverKey}: ${localName},`);
  }

  return `    ${type.typeName}: {\n${entries.join("\n")}\n    },`;
}

function getResolveTypeExpression(
  fieldPattern: AutoGeneratedResolveType["fieldPattern"],
): string {
  const { usedFieldNames } = fieldPattern;

  if (usedFieldNames.size === 1) {
    const fieldName = [...usedFieldNames][0]!;
    return `obj.${fieldName}`;
  }

  const expressions = TYPENAME_FIELD_NAMES.filter((name) =>
    usedFieldNames.has(name),
  ).map((name) => `obj.${name}`);

  return expressions.join(" ?? ");
}

function buildResolveTypeObjType(
  fieldPattern: AutoGeneratedResolveType["fieldPattern"],
): string {
  const fields = TYPENAME_FIELD_NAMES.filter((name) =>
    fieldPattern.usedFieldNames.has(name),
  ).map((name) => `${name}: string`);

  return `{ ${fields.join("; ")} }`;
}

function buildAutoResolveTypeEntry(
  autoResolveType: AutoGeneratedResolveType,
): string {
  const expression = getResolveTypeExpression(autoResolveType.fieldPattern);
  const objType = buildResolveTypeObjType(autoResolveType.fieldPattern);
  return `    ${autoResolveType.unionTypeName}: {\n      __resolveType: (obj: ${objType}) => ${expression},\n    },`;
}

function buildTypeEntries(
  resolverInfo: ResolverInfo,
  customScalars: ReadonlyArray<CollectedScalarType>,
): string[] {
  const typeEntries: string[] = [];
  const hasCustomScalars = customScalars.length > 0;

  if (hasCustomScalars) {
    typeEntries.push(...buildScalarResolverEntries(customScalars));
  }

  const typesWithFields = new Map<string, TypeResolvers>();
  for (const type of resolverInfo.types) {
    typesWithFields.set(type.typeName, type);
  }

  const abstractResolversByType = new Map<string, AbstractTypeResolverInfo>();
  for (const abstractResolver of resolverInfo.abstractTypeResolvers) {
    abstractResolversByType.set(abstractResolver.typeName, abstractResolver);
  }

  const autoResolveTypeByUnion = new Map<string, AutoGeneratedResolveType>(
    resolverInfo.autoGeneratedResolveTypes.map((r) => [r.unionTypeName, r]),
  );

  const discriminatorResolveTypeByUnion = new Map<
    string,
    DiscriminatorResolveTypeInfo
  >(resolverInfo.discriminatorResolveTypes.map((r) => [r.unionTypeName, r]));

  const allTypeNames = new Set<string>([
    ...typesWithFields.keys(),
    ...abstractResolversByType.keys(),
    ...autoResolveTypeByUnion.keys(),
    ...discriminatorResolveTypeByUnion.keys(),
  ]);
  const sortedTypeNames = [...allTypeNames].sort();

  for (const typeName of sortedTypeNames) {
    const typeWithFields = typesWithFields.get(typeName);
    const abstractResolver = abstractResolversByType.get(typeName) ?? null;
    const autoResolveType = autoResolveTypeByUnion.get(typeName);
    const discriminatorResolveType =
      discriminatorResolveTypeByUnion.get(typeName);

    if (typeWithFields !== undefined) {
      typeEntries.push(
        buildTypeResolverEntry(typeWithFields, abstractResolver),
      );
    } else if (abstractResolver !== null) {
      typeEntries.push(buildAbstractOnlyTypeEntry(abstractResolver));
    } else if (discriminatorResolveType !== undefined) {
      typeEntries.push(
        buildDiscriminatorResolveTypeEntry(discriminatorResolveType),
      );
    } else if (autoResolveType !== undefined) {
      typeEntries.push(buildAutoResolveTypeEntry(autoResolveType));
    }
  }

  return typeEntries;
}

interface EmitResolversCodeParams {
  readonly resolverInfo: ResolverInfo;
  readonly outputDir: string;
  readonly customScalars: ReadonlyArray<CollectedScalarType>;
  readonly numericEnums: ReadonlyArray<NumericEnumInfo>;
  readonly stringEnumMappings: ReadonlyArray<StringEnumMappingInfo>;
  readonly importExtension: ImportExtension;
}

export function emitResolversCode(params: EmitResolversCodeParams): string {
  const {
    resolverInfo,
    outputDir,
    customScalars,
    numericEnums,
    stringEnumMappings,
    importExtension,
  } = params;
  const hasCustomScalars = customScalars.length > 0;
  const imports: string[] = [];

  if (hasCustomScalars) {
    imports.push('import { GraphQLScalarType } from "graphql";');
  }

  const importsByFile = collectResolverImports(resolverInfo);
  imports.push(
    ...buildResolverImports({ importsByFile, outputDir, importExtension }),
  );

  if (hasCustomScalars) {
    const scalarTypeImports = collectScalarTypeImports(customScalars);
    const scalarImports = buildScalarTypeImports({
      scalarTypeImports,
      outputDir,
      importExtension,
    });
    imports.push(...scalarImports);
  }

  const numericEnumResolverEntries = buildNumericEnumResolvers(numericEnums);
  const stringEnumResolverEntries =
    buildStringEnumResolvers(stringEnumMappings);
  const typeEntries = buildTypeEntries(resolverInfo, customScalars);

  const allEntries = [
    ...numericEnumResolverEntries,
    ...stringEnumResolverEntries,
    ...typeEntries,
  ];

  const functionSignature = hasCustomScalars
    ? `export function createResolvers({ scalars }: ${buildScalarsArgumentType(customScalars)})`
    : "export function createResolvers()";

  const importSection = imports.length > 0 ? `${imports.join("\n")}\n\n` : "";

  return `${GENERATED_FILE_HEADER}

${importSection}${functionSignature} {
  return {
${allEntries.join("\n")}
  };
}
`;
}
