import { type DocumentNode, print } from "graphql";

const GENERATED_FILE_HEADER =
  "# This file is auto-generated by gqlkit. DO NOT EDIT.";

export function emitSdlContent(documentNode: DocumentNode): string {
  const sdl = print(documentNode);
  return `${GENERATED_FILE_HEADER}\n\n${sdl}`;
}
