// This file is auto-generated by gqlkit. DO NOT EDIT.

import type { DocumentNode } from "graphql";

export const typeDefs: DocumentNode = {
  "kind": "Document",
  "definitions": [
    {
      "kind": "InterfaceTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "Node"
      },
      "fields": [],
      "description": {
        "kind": "StringValue",
        "value": "Node interface - represents any entity with a unique identifier.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "Post"
      },
      "fields": [],
      "description": {
        "kind": "StringValue",
        "value": "Post type that implements Node.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      },
      "interfaces": [
        {
          "kind": "NamedType",
          "name": {
            "kind": "Name",
            "value": "Node"
          }
        }
      ]
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "SearchResult"
      },
      "fields": [],
      "description": {
        "kind": "StringValue",
        "value": "Union type of User and Post (both implementing Node via GqlTypeDef).\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "User"
      },
      "fields": [],
      "description": {
        "kind": "StringValue",
        "value": "User type that implements Node.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      },
      "interfaces": [
        {
          "kind": "NamedType",
          "name": {
            "kind": "Name",
            "value": "Node"
          }
        }
      ]
    }
  ]
} as DocumentNode;
