// This file is auto-generated by gqlkit. DO NOT EDIT.

import { search as Query$search } from "../schema/query.js";

export function createResolvers() {
  return {
    Query: {
      search: Query$search,
    },
  };
}
