// This file is auto-generated by gqlkit. DO NOT EDIT.

import { getFormats, getLevel, getStatus, priority, tasks, updateStatus } from "../schema/types.js";

export function createResolvers() {
  return {
    GetStatusPayload: {
      ACTIVE: "active",
      INACTIVE: "inactive",
      PENDING: "pending",
    },
    GetLevelPayload: {
      BEGINNER: "beginner",
      INTERMEDIATE: "intermediate",
      ADVANCED: "advanced",
    },
    GetFormatsPayload: {
      SIMPLE_WORD: "simpleWord",
      TWO_WORDS: "twoWords",
      THREE_WORDS: "THREE_WORDS",
      KEBAB_CASE_VALUE: "kebab-case-value",
      SNAKE_CASE_VALUE: "snake_case_value",
      MIXED_CASE: "MixedCASE",
    },
    UpdateStatusPayload: {
      SUCCESS: "success",
      FAILURE: "failure",
      PARTIAL_SUCCESS: "partialSuccess",
    },
    TaskPriorityPayload: {
      LOW: "low",
      MEDIUM: "medium",
      HIGH: "high",
      CRITICAL: "critical",
    },
    Mutation: {
      updateStatus: updateStatus,
    },
    Query: {
      getFormats: getFormats,
      getLevel: getLevel,
      getStatus: getStatus,
      tasks: tasks,
    },
    Task: {
      priority: priority,
    },
  };
}
