// This file is auto-generated by gqlkit. DO NOT EDIT.

import { createUserErrorIsTypeOf as CreateUserError$__isTypeOf, createUserSuccessIsTypeOf as CreateUserSuccess$__isTypeOf, createUser as Mutation$createUser, updateUser as Mutation$updateUser, posts as Query$posts, updateUserErrorIsTypeOf as UpdateUserError$__isTypeOf, updateUserPayloadResolveType as UpdateUserPayload$__resolveType, updateUserSuccessIsTypeOf as UpdateUserSuccess$__isTypeOf } from "../schema/types.js";

export function createResolvers() {
  return {
    CreateUserError: {
      __isTypeOf: CreateUserError$__isTypeOf,
    },
    CreateUserPayload: {
      __resolveType: (obj) => obj.__typename,
    },
    CreateUserSuccess: {
      __isTypeOf: CreateUserSuccess$__isTypeOf,
    },
    Mutation: {
      createUser: Mutation$createUser,
      updateUser: Mutation$updateUser,
    },
    Query: {
      posts: Query$posts,
    },
    UpdateUserError: {
      __isTypeOf: UpdateUserError$__isTypeOf,
    },
    UpdateUserPayload: {
      __resolveType: UpdateUserPayload$__resolveType,
    },
    UpdateUserSuccess: {
      __isTypeOf: UpdateUserSuccess$__isTypeOf,
    },
  };
}
