// This file is auto-generated by gqlkit. DO NOT EDIT.

import type { DocumentNode } from "graphql";

export const typeDefs: DocumentNode = {
  "kind": "Document",
  "definitions": [
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "CreateUserError"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "code"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "String"
              }
            }
          }
        },
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "message"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "String"
              }
            }
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "CreateUserError type - exported named type for union member.\nHas __typename field to enable auto-generated resolveType.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "UnionTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "CreateUserPayload"
      },
      "types": [
        {
          "kind": "NamedType",
          "name": {
            "kind": "Name",
            "value": "CreateUserError"
          }
        },
        {
          "kind": "NamedType",
          "name": {
            "kind": "Name",
            "value": "CreateUserSuccess"
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "Defined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "CreateUserSuccess"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "user"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "User"
              }
            }
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "CreateUserSuccess type - exported named type for union member.\nHas __typename field to enable auto-generated resolveType.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "Mutation"
      },
      "fields": []
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "Post"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "id"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "String"
              }
            }
          }
        },
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "title"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "String"
              }
            }
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "Post type for query test.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "Query"
      },
      "fields": []
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "UpdateUserError"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "code"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "String"
              }
            }
          }
        },
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "message"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "String"
              }
            }
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "UpdateUserError type - exported named type for union member.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "UnionTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "UpdateUserPayload"
      },
      "types": [
        {
          "kind": "NamedType",
          "name": {
            "kind": "Name",
            "value": "UpdateUserError"
          }
        },
        {
          "kind": "NamedType",
          "name": {
            "kind": "Name",
            "value": "UpdateUserSuccess"
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "Union type for UpdateUserPayload.\nThis type is explicitly named to allow defineResolveType to target it.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "UpdateUserSuccess"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "user"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "User"
              }
            }
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "UpdateUserSuccess type - exported named type for union member.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "User"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "email"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "String"
              }
            }
          }
        },
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "id"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "String"
              }
            }
          }
        },
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "name"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "String"
              }
            }
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "User type - named type for success case.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeExtension",
      "name": {
        "kind": "Name",
        "value": "Mutation"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "createUser"
          },
          "arguments": [
            {
              "kind": "InputValueDefinition",
              "name": {
                "kind": "Name",
                "value": "name"
              },
              "type": {
                "kind": "NonNullType",
                "type": {
                  "kind": "NamedType",
                  "name": {
                    "kind": "Name",
                    "value": "String"
                  }
                }
              }
            },
            {
              "kind": "InputValueDefinition",
              "name": {
                "kind": "Name",
                "value": "email"
              },
              "type": {
                "kind": "NonNullType",
                "type": {
                  "kind": "NamedType",
                  "name": {
                    "kind": "Name",
                    "value": "String"
                  }
                }
              }
            }
          ],
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "CreateUserPayload"
              }
            }
          },
          "description": {
            "kind": "StringValue",
            "value": "Test case 1: Mutation WITHOUT manual defineResolveType\n\nThis mutation returns a union of named types (CreateUserSuccess | CreateUserError).\nBoth types have __typename fields, so auto-generated __resolveType is used.\n\nExpected: CreateUserPayload uses auto-generated __resolveType: (obj) => obj.__typename\n\nDefined in: src/gqlkit/schema/types.ts",
            "block": true
          }
        },
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "updateUser"
          },
          "arguments": [
            {
              "kind": "InputValueDefinition",
              "name": {
                "kind": "Name",
                "value": "id"
              },
              "type": {
                "kind": "NonNullType",
                "type": {
                  "kind": "NamedType",
                  "name": {
                    "kind": "Name",
                    "value": "String"
                  }
                }
              }
            },
            {
              "kind": "InputValueDefinition",
              "name": {
                "kind": "Name",
                "value": "name"
              },
              "type": {
                "kind": "NonNullType",
                "type": {
                  "kind": "NamedType",
                  "name": {
                    "kind": "Name",
                    "value": "String"
                  }
                }
              }
            }
          ],
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "UpdateUserPayload"
              }
            }
          },
          "description": {
            "kind": "StringValue",
            "value": "Test case 2: Mutation WITH manual defineResolveType\n\nThis mutation uses UpdateUserPayload which has a manual defineResolveType.\nThe manual resolveType takes priority over any auto-generated one.\n\nExpected behavior:\n- CreateUserPayload: uses auto-generated __resolveType: (obj) => obj.__typename\n- UpdateUserPayload: uses manual updateUserPayloadResolveType (priority over auto)\n\nDefined in: src/gqlkit/schema/types.ts",
            "block": true
          }
        }
      ]
    },
    {
      "kind": "ObjectTypeExtension",
      "name": {
        "kind": "Name",
        "value": "Query"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "posts"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "ListType",
              "type": {
                "kind": "NonNullType",
                "type": {
                  "kind": "NamedType",
                  "name": {
                    "kind": "Name",
                    "value": "Post"
                  }
                }
              }
            }
          },
          "description": {
            "kind": "StringValue",
            "value": "Query to fetch posts.\n\nDefined in: src/gqlkit/schema/types.ts",
            "block": true
          }
        }
      ]
    }
  ]
} as DocumentNode;
