import {
  collectResolveTypes,
  collectTypenameExtractions,
  flattenIntersectionMembers,
  generateAutoTypes,
  validateDiscriminatorFields,
  validateNameCollisions,
  validateSchemaTypenames,
  validateTypenames,
} from "../auto-type-generator/index.js";
import type { ImportExtension } from "../config/types.js";
import type { ResolvedDiscriminatorFieldsMap } from "../config-loader/index.js";
import type { Diagnostic } from "../core/index.js";
import type { ExtractResolversResult } from "../resolver-extractor/index.js";
import type { DirectiveDefinitionInfo } from "../shared/directive-definition-extractor.js";
import {
  type CollectedScalarType,
  type CollectedTypesResult,
  convertToGraphQL,
  type ExtractedTypeInfo,
} from "../type-extractor/index.js";
import { buildDocumentNode } from "./builder/ast-builder.js";
import { emitResolversCode, emitTypeDefsCode } from "./emitter/code-emitter.js";
import { emitSdlContent } from "./emitter/sdl-emitter.js";
import {
  type IntegratedResult,
  integrate,
} from "./integrator/result-integrator.js";
import { pruneDocumentNode } from "./pruner/schema-pruner.js";
import { collectResolverInfo } from "./resolver-collector/resolver-collector.js";

export interface GenerateSchemaInput {
  readonly typesResult: CollectedTypesResult;
  readonly extractedTypes: ReadonlyArray<ExtractedTypeInfo>;
  readonly resolversResult: ExtractResolversResult;
  readonly outputDir: string;
  readonly customScalarNames: ReadonlyArray<string> | null;
  readonly customScalars: ReadonlyArray<CollectedScalarType> | null;
  readonly directiveDefinitions: ReadonlyArray<DirectiveDefinitionInfo> | null;
  readonly enablePruning: boolean;
  readonly sourceRoot: string | null;
  readonly knownTypeNames: ReadonlySet<string> | null;
  readonly importExtension: ImportExtension;
  readonly discriminatorFields: ResolvedDiscriminatorFieldsMap;
}

export interface GenerateSchemaResult {
  readonly typeDefsCode: string;
  readonly sdlContent: string;
  readonly resolversCode: string;
  readonly diagnostics: ReadonlyArray<Diagnostic>;
  readonly hasErrors: boolean;
  /** Names of types removed by pruning (empty when pruning is disabled). */
  readonly prunedTypes: ReadonlyArray<string>;
}

/**
 * Drop resolver-map sources that target pruned types so the emitted
 * resolvers stay consistent with the pruned schema. Resolvers for a pruned
 * type could never be invoked anyway (the type is unreachable from every
 * root operation type).
 */
function omitPrunedTypes(
  integratedResult: IntegratedResult,
  prunedTypeNames: ReadonlySet<string>,
): IntegratedResult {
  if (prunedTypeNames.size === 0) {
    return integratedResult;
  }
  return {
    ...integratedResult,
    typeExtensions: integratedResult.typeExtensions.filter(
      (e) => !prunedTypeNames.has(e.targetTypeName),
    ),
    abstractTypeResolvers: integratedResult.abstractTypeResolvers.filter(
      (r) => !prunedTypeNames.has(r.targetTypeName),
    ),
    autoGeneratedUnions: integratedResult.autoGeneratedUnions.filter(
      (u) => !prunedTypeNames.has(u.name),
    ),
    typenameAutoResolveTypes: integratedResult.typenameAutoResolveTypes.filter(
      (t) => !prunedTypeNames.has(t.abstractTypeName),
    ),
    discriminatorResolveTypes:
      integratedResult.discriminatorResolveTypes.filter(
        (r) => !prunedTypeNames.has(r.unionTypeName),
      ),
    numericEnums: integratedResult.numericEnums.filter(
      (e) => !prunedTypeNames.has(e.enumName),
    ),
    stringEnumMappings: integratedResult.stringEnumMappings.filter(
      (e) => !prunedTypeNames.has(e.enumName),
    ),
  };
}

export function generateSchema(
  input: GenerateSchemaInput,
): GenerateSchemaResult {
  const {
    typesResult,
    extractedTypes,
    resolversResult,
    outputDir,
    customScalarNames,
    customScalars,
    directiveDefinitions,
    enablePruning,
    sourceRoot,
    knownTypeNames,
    importExtension,
  } = input;

  const autoTypeResult = generateAutoTypes({
    extractedTypes,
    resolversResult,
    knownTypeNames: knownTypeNames ?? new Set(),
    discriminatorFields: input.discriminatorFields,
  });

  const autoTypeErrors = autoTypeResult.diagnostics.filter(
    (d) => d.severity === "error",
  );
  if (autoTypeErrors.length > 0) {
    return {
      typeDefsCode: "",
      sdlContent: "",
      resolversCode: "",
      diagnostics: autoTypeResult.diagnostics,
      hasErrors: true,
      prunedTypes: [],
    };
  }

  const userDefinedTypes = extractedTypes.map((t) => ({
    name: t.metadata.name,
    sourceLocation: t.metadata.sourceLocation,
  }));

  const collisionResult = validateNameCollisions({
    userDefinedTypes,
    autoGeneratedTypes: autoTypeResult.autoGeneratedTypes,
    sourceRoot,
  });

  if (collisionResult.hasCollisions) {
    return {
      typeDefsCode: "",
      sdlContent: "",
      resolversCode: "",
      diagnostics: collisionResult.diagnostics,
      hasErrors: true,
      prunedTypes: [],
    };
  }

  // Flatten intersection-expanded inline object members for discriminator unions.
  // TypeScript distributes intersections over unions, creating duplicate members
  // that must be merged before discriminator field validation.
  const flattenedExtractedTypes = flattenIntersectionMembers({
    extractedTypes: autoTypeResult.updatedExtractedTypes,
    discriminatorFields: input.discriminatorFields,
  });

  // Re-convert to GraphQL types using updated extracted types
  // This resolves __INLINE_OBJECT__ references to auto-generated type names
  const updatedConversionResult = convertToGraphQL(flattenedExtractedTypes);
  const typeMap = new Map(
    flattenedExtractedTypes.map((t) => [t.metadata.name, t]),
  );

  // Validate discriminator fields against extracted types
  const inlineDiscriminatorUnionNames = new Set(
    autoTypeResult.inlineDiscriminatorResolveTypes.map(
      (rt) => rt.unionTypeName,
    ),
  );
  const discriminatorValidationResult = validateDiscriminatorFields({
    discriminatorFields: input.discriminatorFields,
    extractedTypes: flattenedExtractedTypes,
    typeMap,
    inlineDiscriminatorUnionNames,
  });
  const discriminatorErrors = discriminatorValidationResult.diagnostics.filter(
    (d) => d.severity === "error",
  );
  if (discriminatorErrors.length > 0) {
    return {
      typeDefsCode: "",
      sdlContent: "",
      resolversCode: "",
      diagnostics: discriminatorValidationResult.diagnostics,
      hasErrors: true,
      prunedTypes: [],
    };
  }

  const discriminatorWarnings =
    discriminatorValidationResult.diagnostics.filter(
      (d) => d.severity === "warning",
    );

  const updatedTypesResult: CollectedTypesResult = {
    types: updatedConversionResult.types,
    diagnostics: {
      errors: [
        ...typesResult.diagnostics.errors,
        ...updatedConversionResult.diagnostics.filter(
          (d) => d.severity === "error",
        ),
        ...autoTypeResult.diagnostics.filter((d) => d.severity === "error"),
      ],
      warnings: [
        ...typesResult.diagnostics.warnings,
        ...updatedConversionResult.diagnostics.filter(
          (d) => d.severity === "warning",
        ),
        ...autoTypeResult.diagnostics.filter((d) => d.severity === "warning"),
        ...discriminatorWarnings,
      ],
    },
  };

  const discriminatorFieldUnionNames = new Set(
    input.discriminatorFields.keys(),
  );

  const {
    discriminatorResolveTypesResult,
    mergedDiscriminatorResolveTypes,
    typenameResolveTypesResult,
  } = collectResolveTypes({
    validatedEntries: discriminatorValidationResult.validatedEntries,
    abstractTypeResolvers:
      autoTypeResult.updatedResolversResult.abstractTypeResolvers,
    extractedTypes: flattenedExtractedTypes,
    typeMap,
    inlineDiscriminatorResolveTypes:
      autoTypeResult.inlineDiscriminatorResolveTypes,
    discriminatorFieldUnionNames,
  });

  const typenameExtractions = collectTypenameExtractions({
    extractedTypes: flattenedExtractedTypes,
    typeMap,
    discriminatorFieldUnionNames,
  });

  const typenameValidationDiagnostics: Diagnostic[] = [];

  for (const extraction of typenameExtractions) {
    const abstractType = typeMap.get(extraction.abstractTypeName);
    if (!abstractType) {
      continue;
    }
    const validationResult = validateTypenames({
      extractionResult: extraction,
      sourceLocation: abstractType.metadata.sourceLocation,
      inlineObjectMembers: abstractType.inlineObjectMembers,
    });
    typenameValidationDiagnostics.push(...validationResult.diagnostics);
  }

  const schemaTypenameValidationResult = validateSchemaTypenames({
    objectTypes: flattenedExtractedTypes,
    typeMap,
  });
  typenameValidationDiagnostics.push(
    ...schemaTypenameValidationResult.diagnostics,
  );

  if (typenameValidationDiagnostics.length > 0) {
    return {
      typeDefsCode: "",
      sdlContent: "",
      resolversCode: "",
      diagnostics: typenameValidationDiagnostics,
      hasErrors: true,
      prunedTypes: [],
    };
  }

  const generatedInlineObjectTypes =
    typenameResolveTypesResult.generatedInlineObjectTypes;

  // Collect all generated object types that need to be added as union members
  // (both typename-based and discriminator-based inline objects)
  const discriminatorGeneratedObjectTypes =
    discriminatorResolveTypesResult.generatedObjectTypes;

  const updatedTypesForIntegration: CollectedTypesResult =
    generatedInlineObjectTypes.length > 0 ||
    discriminatorGeneratedObjectTypes.length > 0
      ? {
          types: updatedTypesResult.types.map((type) => {
            if (type.kind !== "Union") {
              return type;
            }
            const typenameInlineTypes = generatedInlineObjectTypes.filter(
              (g) => g.abstractTypeName === type.name,
            );
            const discriminatorInlineTypes =
              discriminatorGeneratedObjectTypes.filter(
                (g) =>
                  g.generatedFrom !== null &&
                  g.generatedFrom.parentTypeName === type.name,
              );
            if (
              typenameInlineTypes.length === 0 &&
              discriminatorInlineTypes.length === 0
            ) {
              return type;
            }
            const newMembers = [
              ...typenameInlineTypes.map((g) => g.typeName),
              ...discriminatorInlineTypes.map((g) => g.name),
            ];
            return {
              ...type,
              unionMembers: [
                ...(type.unionMembers ?? []),
                ...newMembers,
              ].sort(),
            };
          }),
          diagnostics: updatedTypesResult.diagnostics,
        }
      : updatedTypesResult;

  const allAutoGeneratedTypes = [
    ...autoTypeResult.autoGeneratedTypes,
    ...typenameResolveTypesResult.generatedObjectTypes,
    ...discriminatorGeneratedObjectTypes,
  ];

  const integratedResult = integrate({
    typesResult: updatedTypesForIntegration,
    resolversResult: autoTypeResult.updatedResolversResult,
    customScalarNames,
    collectedScalars: customScalars,
    directiveDefinitions,
    autoGeneratedTypes: allAutoGeneratedTypes,
    typenameAutoResolveTypes: typenameResolveTypesResult.autoResolveTypes,
    discriminatorResolveTypes: mergedDiscriminatorResolveTypes,
    tsAliasToGraphQLNameMap: autoTypeResult.tsAliasToGraphQLNameMap,
  });

  let documentNode = buildDocumentNode(integratedResult, { sourceRoot });
  let prunedTypes: ReadonlyArray<string> = [];

  // Prune only on the success path: an errored result is never written, and
  // its document may be arbitrarily incomplete.
  if (enablePruning && !integratedResult.hasErrors) {
    const pruneResult = pruneDocumentNode(documentNode);
    documentNode = pruneResult.documentNode;
    prunedTypes = pruneResult.removedTypes;
  }

  const typeDefsCode = emitTypeDefsCode(documentNode);
  const sdlContent = emitSdlContent(documentNode);

  // The resolver map must mirror the (possibly pruned) schema: resolver
  // entries for types absent from typeDefs are rejected by
  // makeExecutableSchema at the user's runtime.
  const prunedTypeNames = new Set(prunedTypes);
  const resolverSource = omitPrunedTypes(integratedResult, prunedTypeNames);
  const resolverInfo = collectResolverInfo(resolverSource);
  const resolversCode = emitResolversCode({
    resolverInfo,
    outputDir,
    customScalars: (customScalars ?? []).filter(
      (s) => !prunedTypeNames.has(s.scalarName),
    ),
    numericEnums: resolverSource.numericEnums,
    stringEnumMappings: resolverSource.stringEnumMappings,
    importExtension,
  });

  return {
    typeDefsCode,
    sdlContent,
    resolversCode,
    diagnostics: integratedResult.diagnostics,
    hasErrors: integratedResult.hasErrors,
    prunedTypes,
  };
}
