// This file is auto-generated by gqlkit. DO NOT EDIT.

import type { DocumentNode } from "graphql";

export const typeDefs: DocumentNode = {
  kind: "Document",
  definitions: [
    {
      kind: "ScalarTypeDefinition",
      name: {
        kind: "Name",
        value: "DateTime",
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "Mutation",
      },
      fields: [],
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "Post",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "authorId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "content",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "createdAt",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "DateTime",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "id",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "priority",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "title",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/gqlkit/schema/post.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "Query",
      },
      fields: [],
    },
    {
      kind: "ObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "User",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "createdAt",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "DateTime",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "email",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "id",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "name",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "status",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/gqlkit/schema/user.ts",
        block: true,
      },
    },
    {
      kind: "InputObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "CreatePostInput",
      },
      fields: [
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "authorId",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "content",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "priority",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "title",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/gqlkit/schema/post.ts",
        block: true,
      },
    },
    {
      kind: "InputObjectTypeDefinition",
      name: {
        kind: "Name",
        value: "CreateUserInput",
      },
      fields: [
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "email",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "name",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "String",
              },
            },
          },
        },
        {
          kind: "InputValueDefinition",
          name: {
            kind: "Name",
            value: "status",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "String",
            },
          },
        },
      ],
      description: {
        kind: "StringValue",
        value: "Defined in: src/gqlkit/schema/user.ts",
        block: true,
      },
    },
    {
      kind: "ObjectTypeExtension",
      name: {
        kind: "Name",
        value: "Mutation",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "createPost",
          },
          arguments: [
            {
              kind: "InputValueDefinition",
              name: {
                kind: "Name",
                value: "input",
              },
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "CreatePostInput",
                  },
                },
              },
            },
          ],
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "Post",
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/gqlkit/schema/post.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "createUser",
          },
          arguments: [
            {
              kind: "InputValueDefinition",
              name: {
                kind: "Name",
                value: "input",
              },
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "CreateUserInput",
                  },
                },
              },
            },
          ],
          type: {
            kind: "NonNullType",
            type: {
              kind: "NamedType",
              name: {
                kind: "Name",
                value: "User",
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/gqlkit/schema/user.ts",
            block: true,
          },
        },
      ],
    },
    {
      kind: "ObjectTypeExtension",
      name: {
        kind: "Name",
        value: "Post",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "author",
          },
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "User",
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/gqlkit/schema/post.ts",
            block: true,
          },
        },
      ],
    },
    {
      kind: "ObjectTypeExtension",
      name: {
        kind: "Name",
        value: "Query",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "allPosts",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "Post",
                  },
                },
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/gqlkit/schema/post.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "allUsers",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "User",
                  },
                },
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/gqlkit/schema/user.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "post",
          },
          arguments: [
            {
              kind: "InputValueDefinition",
              name: {
                kind: "Name",
                value: "id",
              },
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "String",
                  },
                },
              },
            },
          ],
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "Post",
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/gqlkit/schema/post.ts",
            block: true,
          },
        },
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "user",
          },
          arguments: [
            {
              kind: "InputValueDefinition",
              name: {
                kind: "Name",
                value: "id",
              },
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "String",
                  },
                },
              },
            },
          ],
          type: {
            kind: "NamedType",
            name: {
              kind: "Name",
              value: "User",
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/gqlkit/schema/user.ts",
            block: true,
          },
        },
      ],
    },
    {
      kind: "ObjectTypeExtension",
      name: {
        kind: "Name",
        value: "User",
      },
      fields: [
        {
          kind: "FieldDefinition",
          name: {
            kind: "Name",
            value: "posts",
          },
          type: {
            kind: "NonNullType",
            type: {
              kind: "ListType",
              type: {
                kind: "NonNullType",
                type: {
                  kind: "NamedType",
                  name: {
                    kind: "Name",
                    value: "Post",
                  },
                },
              },
            },
          },
          description: {
            kind: "StringValue",
            value: "Defined in: src/gqlkit/schema/user.ts",
            block: true,
          },
        },
      ],
    },
  ],
} as DocumentNode;
