// This file is auto-generated by gqlkit. DO NOT EDIT.

export function createResolvers() {
  return {
    orderStatus: {
      PENDING: "ORDER_STATUS_PENDING",
      SHIPPED: "ORDER_STATUS_SHIPPED",
      DELIVERED: "ORDER_STATUS_DELIVERED",
    },
  };
}
