// This file is auto-generated by gqlkit. DO NOT EDIT.

import { nodeResolveType as Node$__resolveType } from "../schema/node.js";
import { users as Query$users } from "../schema/query.js";

export function createResolvers() {
  return {
    Node: {
      __resolveType: Node$__resolveType,
    },
    Query: {
      users: Query$users,
    },
  };
}
