// This file is auto-generated by gqlkit. DO NOT EDIT.

import { user } from "../query.js";

export function createResolvers(): {
  Query: {
    user: typeof user;
  };
} {
  return {
    Query: {
      user: user,
    },
  };
}
