// This file is auto-generated by gqlkit. DO NOT EDIT.

import { GraphQLScalarType } from "graphql";
import { entityResolveType } from "../schema/interfaces.js";
import { articles } from "../schema/query.js";
import type { DateTime } from "../schema/interfaces.js";

export function createResolvers({ scalars }: {
  scalars: {
    DateTime: GraphQLScalarType<DateTime, DateTime>;
  };
}) {
  return {
    DateTime: scalars.DateTime,
    Entity: {
      __resolveType: entityResolveType,
    },
    Query: {
      articles: articles,
    },
  };
}
