// This file is auto-generated by gqlkit. DO NOT EDIT.

import { animals as Query$animals } from "../schema/query.js";
import { catIsTypeOf as Cat$__isTypeOf, dogIsTypeOf as Dog$__isTypeOf } from "../schema/types.js";

export function createResolvers() {
  return {
    Cat: {
      __isTypeOf: Cat$__isTypeOf,
    },
    Dog: {
      __isTypeOf: Dog$__isTypeOf,
    },
    Query: {
      animals: Query$animals,
    },
  };
}
