// This file is auto-generated by gqlkit. DO NOT EDIT.

import { alertReceived as Subscription$alertReceived, messageAdded as Subscription$messageAdded, notificationReceived as Subscription$notificationReceived } from "../schema/subscription.js";

export function createResolvers() {
  return {
    Subscription: {
      alertReceived: { subscribe: Subscription$alertReceived, resolve: (event: unknown) => event },
      messageAdded: { subscribe: Subscription$messageAdded, resolve: (event: unknown) => event },
      notificationReceived: { subscribe: Subscription$notificationReceived, resolve: (event: unknown) => event },
    },
  };
}
