// This file is auto-generated by gqlkit. DO NOT EDIT.

import { alertReceived as Subscription$alertReceived, messageAdded as Subscription$messageAdded, notificationReceived as Subscription$notificationReceived, orderUpdated as Subscription$orderUpdated } from "../schema/subscription.js";

export function createResolvers() {
  return {
    Subscription: {
      alertReceived: { subscribe: Subscription$alertReceived },
      messageAdded: { subscribe: Subscription$messageAdded },
      notificationReceived: { subscribe: Subscription$notificationReceived },
      orderUpdated: { subscribe: Subscription$orderUpdated },
    },
  };
}
