// This file is auto-generated by gqlkit. DO NOT EDIT.

import { user as Query$user } from "../schema/query.js";

export function createResolvers() {
  return {
    Query: {
      user: Query$user,
    },
  };
}
