// This file is auto-generated by gqlkit. DO NOT EDIT.

import type { DocumentNode } from "graphql";

export const typeDefs: DocumentNode = {
  "kind": "Document",
  "definitions": [
    {
      "kind": "InterfaceTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "Node"
      },
      "fields": [],
      "description": {
        "kind": "StringValue",
        "value": "The Node interface for Relay-style pagination.\n\nDefined in: src/gqlkit/schema/node.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "User"
      },
      "fields": [],
      "description": {
        "kind": "StringValue",
        "value": "A user in the system.\n\nDefined in: src/gqlkit/schema/user.ts",
        "block": true
      },
      "interfaces": [
        {
          "kind": "NamedType",
          "name": {
            "kind": "Name",
            "value": "Node"
          }
        }
      ]
    }
  ]
} as DocumentNode;
