/**
 * Remaps abstract resolver (`resolveType`/`isTypeOf`) target type names from
 * TS aliases to GraphQL names, then validates the remapped resolvers against
 * the schema's base types.
 */

import type {
  DiscriminatorResolveTypeInfo,
  TypenameAutoResolveTypeInfo,
} from "../../auto-type-generator/index.js";
import type { Diagnostic } from "../../core/index.js";
import type { AbstractResolverInfo } from "../../resolver-extractor/index.js";
import { validateAbstractResolvers } from "../validator/abstract-resolver-validator.js";
import type { AutoGeneratedUnionInfo, BaseType } from "./type-mapper.js";

export interface RemapAndValidateAbstractResolversParams {
  readonly abstractResolvers: ReadonlyArray<AbstractResolverInfo>;
  readonly tsAliasToGraphQLNameMap: ReadonlyMap<string, string> | null;
  readonly baseTypes: ReadonlyArray<BaseType>;
  readonly typenameAutoResolveTypes: ReadonlyArray<TypenameAutoResolveTypeInfo> | null;
  readonly autoGeneratedUnions: ReadonlyArray<AutoGeneratedUnionInfo>;
  readonly discriminatorResolveTypes: ReadonlyArray<DiscriminatorResolveTypeInfo> | null;
}

export interface RemapAndValidateAbstractResolversResult {
  readonly remappedAbstractResolvers: ReadonlyArray<AbstractResolverInfo>;
  readonly diagnostics: ReadonlyArray<Diagnostic>;
}

export function remapAndValidateAbstractResolvers(
  params: RemapAndValidateAbstractResolversParams,
): RemapAndValidateAbstractResolversResult {
  const {
    abstractResolvers,
    tsAliasToGraphQLNameMap,
    baseTypes,
    typenameAutoResolveTypes,
    autoGeneratedUnions,
    discriminatorResolveTypes,
  } = params;

  const typenameAutoResolveTypeNames = new Set([
    ...(typenameAutoResolveTypes?.map((t) => t.abstractTypeName) ?? []),
    ...autoGeneratedUnions
      .filter((u) => u.hasAutoResolveType)
      .map((u) => u.name),
    ...(discriminatorResolveTypes?.map((t) => t.unionTypeName) ?? []),
  ]);

  const aliasMap = tsAliasToGraphQLNameMap ?? new Map<string, string>();

  // Remap abstract resolver target type names from TS aliases to GraphQL names
  // Only remap resolveType resolvers — isTypeOf targets object types, not unions
  const remappedAbstractResolvers =
    aliasMap.size > 0
      ? abstractResolvers.map((resolver) => {
          if (resolver.kind !== "resolveType") return resolver;
          const mappedName = aliasMap.get(resolver.targetTypeName);
          return mappedName !== undefined
            ? { ...resolver, targetTypeName: mappedName }
            : resolver;
        })
      : abstractResolvers;

  const { diagnostics } = validateAbstractResolvers({
    abstractResolvers: remappedAbstractResolvers,
    baseTypes,
    typenameAutoResolveTypeNames,
  });

  return { remappedAbstractResolvers, diagnostics };
}
