// This file is auto-generated by gqlkit. DO NOT EDIT.

import type { DocumentNode } from "graphql";

export const typeDefs: DocumentNode = {
  "kind": "Document",
  "definitions": [
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "ExternalAlpha"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "label"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "String"
              }
            }
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "Defined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "ExternalBeta"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "score"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "Float"
              }
            }
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "Defined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "NullableResult"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "result"
          },
          "type": {
            "kind": "NamedType",
            "name": {
              "kind": "Name",
              "value": "NullableResultResult"
            }
          },
          "description": {
            "kind": "StringValue",
            "value": "Nullable direct union of discovered types",
            "block": true
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "Nullable union with discovered named members.\nTests that nullability is preserved for discovered types.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "UnionTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "NullableResultResult"
      },
      "types": [
        {
          "kind": "NamedType",
          "name": {
            "kind": "Name",
            "value": "ExternalAlpha"
          }
        },
        {
          "kind": "NamedType",
          "name": {
            "kind": "Name",
            "value": "ExternalBeta"
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "Defined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "ObjectTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "SearchResult"
      },
      "fields": [
        {
          "kind": "FieldDefinition",
          "name": {
            "kind": "Name",
            "value": "item"
          },
          "type": {
            "kind": "NonNullType",
            "type": {
              "kind": "NamedType",
              "name": {
                "kind": "Name",
                "value": "SearchResultItem"
              }
            }
          },
          "description": {
            "kind": "StringValue",
            "value": "Non-nullable direct union of discovered types",
            "block": true
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "Direct (non-array) union with discovered named members.\nExternalAlpha and ExternalBeta should be registered with original names.\n\nDefined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    },
    {
      "kind": "UnionTypeDefinition",
      "name": {
        "kind": "Name",
        "value": "SearchResultItem"
      },
      "types": [
        {
          "kind": "NamedType",
          "name": {
            "kind": "Name",
            "value": "ExternalAlpha"
          }
        },
        {
          "kind": "NamedType",
          "name": {
            "kind": "Name",
            "value": "ExternalBeta"
          }
        }
      ],
      "description": {
        "kind": "StringValue",
        "value": "Defined in: src/gqlkit/schema/types.ts",
        "block": true
      }
    }
  ]
} as DocumentNode;
