// This file is auto-generated by gqlkit. DO NOT EDIT.

import { GraphQLScalarType } from "graphql";
import { nodeResolveType as Node$__resolveType, timestampedResolveType as Timestamped$__resolveType } from "../schema/interfaces.js";
import { posts as Query$posts } from "../schema/query.js";
import type { DateTime } from "../schema/interfaces.js";

export function createResolvers({ scalars }: {
  scalars: {
    DateTime: GraphQLScalarType<DateTime, DateTime>;
  };
}) {
  return {
    DateTime: scalars.DateTime,
    Node: {
      __resolveType: Node$__resolveType,
    },
    Query: {
      posts: Query$posts,
    },
    Timestamped: {
      __resolveType: Timestamped$__resolveType,
    },
  };
}
