// This file is auto-generated by gqlkit. DO NOT EDIT.

import { users as Query$users } from "../schema/query.js";

export function createResolvers() {
  return {
    UserStatus: {
      ACTIVE: "active",
      INACTIVE: "inactive",
    },
    Query: {
      users: Query$users,
    },
  };
}
