// This file is auto-generated by gqlkit. DO NOT EDIT.

export function createResolvers() {
  return {
    UserStatus: {
      ACTIVE: "Active",
      INACTIVE: "Inactive",
      PENDING_REVIEW: "PendingReview",
    },
  };
}
