// This file is auto-generated by gqlkit. DO NOT EDIT.

import { tool as Query$tool } from "../schema/query.js";

export function createResolvers() {
  return {
    Query: {
      tool: Query$tool,
    },
  };
}
