// This file is auto-generated by gqlkit. DO NOT EDIT.

import { allUsers } from "../schema/types.js";

export function createResolvers() {
  return {
    Query: {
      allUsers: allUsers,
    },
  };
}
