// This file is auto-generated by gqlkit. DO NOT EDIT.

import { articles, metadata, posts, relatedContent, stats, users } from "../schema/types.js";

export function createResolvers() {
  return {
    Article: {
      relatedContent: relatedContent,
    },
    BlogPost: {
      metadata: metadata,
    },
    Query: {
      articles: articles,
      posts: posts,
      users: users,
    },
    User: {
      stats: stats,
    },
  };
}
