// This file is auto-generated by gqlkit. DO NOT EDIT.

import { createUser as Mutation$createUser, updateUser as Mutation$updateUser, user as Query$user, users as Query$users } from "../schema/types.js";

export function createResolvers() {
  return {
    UserRole: {
      ADMIN: "admin",
      MEMBER: "member",
    },
    Mutation: {
      createUser: Mutation$createUser,
      updateUser: Mutation$updateUser,
    },
    Query: {
      user: Query$user,
      users: Query$users,
    },
  };
}
