// This file is auto-generated by gqlkit. DO NOT EDIT.

import { createPost as Mutation$createPost, findUser as Query$findUser, posts as User$posts } from "../schema/types.js";

export function createResolvers() {
  return {
    Mutation: {
      createPost: Mutation$createPost,
    },
    Query: {
      findUser: Query$findUser,
    },
    User: {
      posts: User$posts,
    },
  };
}
