// This file is auto-generated by gqlkit. DO NOT EDIT.

import { globalId } from "../schema/node.js";
import { node, users } from "../schema/query.js";

export function createResolvers() {
  return {
    Node: {
      globalId: globalId,
    },
    Query: {
      node: node,
      users: users,
    },
  };
}
